package pbui

import (
	"bytes"
	"encoding/json"
	"fmt"
	"path/filepath"
	"strings"
)

type ReactRenderedFile struct {
	Path    string
	Kind    string
	Symbol  string
	Content string
}

func RenderReactPlan(plan ReactPlan) ([]ReactRenderedFile, error) {
	presentationByComponent := map[string]PresentationPlan{}
	for _, presentationPlan := range plan.PresentationPlans {
		presentationByComponent[presentationPlan.ComponentName] = presentationPlan
	}

	var files []ReactRenderedFile
	for _, planned := range plan.Files {
		content, err := renderReactFile(plan, presentationByComponent, planned)
		if err != nil {
			return nil, err
		}
		files = append(files, ReactRenderedFile{Path: planned.Path, Kind: planned.Kind, Symbol: planned.Symbol, Content: content})
	}
	return files, nil
}

func renderReactFile(plan ReactPlan, presentationByComponent map[string]PresentationPlan, planned ReactPlannedFile) (string, error) {
	switch planned.Kind {
	case "package_json":
		return renderPackageJSON(plan), nil
	case "tsconfig":
		return renderTSConfig(), nil
	case "object_type_registry":
		return renderConstJSON("objectTypeDescriptors", plan.ObjectDescriptors)
	case "action_descriptor_registry":
		return renderConstJSON("actionDescriptors", plan.ActionDescriptors)
	case "presentation_type_registry":
		return renderConstJSON("presentationTypeDescriptors", plan.PresentationPlans)
	case "session_slice":
		return renderSessionSlice(), nil
	case "selectors":
		return renderSelectors(), nil
	case "action_request_builder":
		return renderActionRequests(), nil
	case "event_adapter":
		return renderEventAdapters(), nil
	case "command_parser":
		return renderCommandParser(), nil
	case "README":
		return renderPackageReadme(plan), nil
	case "presenter_hook":
		presentationPlan := presentationByComponent[planned.Provenance.ComponentName]
		return renderPresenterHook(presentationPlan), nil
	case "component":
		presentationPlan := presentationByComponent[planned.Provenance.ComponentName]
		return renderComponent(presentationPlan), nil
	case "metadata":
		return renderMetadata(planned.Provenance)
	case "stories":
		presentationPlan := presentationByComponent[planned.Provenance.ComponentName]
		return renderStories(presentationPlan), nil
	case "barrel":
		return renderBarrel(planned.Symbol), nil
	default:
		return fmt.Sprintf("// Planned PBUI React file kind %q for symbol %q.\n", planned.Kind, planned.Symbol), nil
	}
}

func renderPackageJSON(plan ReactPlan) string {
	return fmt.Sprintf(`{
  "name": %q,
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "build": "tsc -p tsconfig.json --noEmit"
  },
  "dependencies": {
    "react": "^19.2.6",
    "react-dom": "^19.2.6"
  },
  "devDependencies": {
    "@types/react": "^19.2.14",
    "@types/react-dom": "^19.2.3",
    "typescript": "~6.0.2"
  }
}
`, plan.PackageName)
}

func renderTSConfig() string {
	return `{
  "compilerOptions": {
    "target": "ES2022",
    "useDefineForClassFields": true,
    "lib": ["ES2022", "DOM", "DOM.Iterable"],
    "allowJs": false,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "ESNext",
    "moduleResolution": "Bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx"
  },
  "include": ["**/*.ts", "**/*.tsx"],
  "exclude": ["**/*.stories.tsx", "node_modules"]
}
`
}

func renderConstJSON(symbol string, value any) (string, error) {
	b, err := json.MarshalIndent(value, "", "  ")
	if err != nil {
		return "", err
	}
	var buf bytes.Buffer
	buf.WriteString("// Generated by DMETA PBUI React target. Do not edit by hand.\n")
	buf.WriteString("// This registry preserves PBUI/Semantic/Interaction metadata for introspection surfaces.\n\n")
	buf.WriteString("export const ")
	buf.WriteString(symbol)
	buf.WriteString(" = ")
	buf.Write(b)
	buf.WriteString(" as const;\n")
	return buf.String(), nil
}

func renderSessionSlice() string {
	return `// Generated by DMETA PBUI React target. Do not edit by hand.

export type PBUIInteractionState =
  | { kind: 'idle' }
  | { kind: 'objectSelected'; semanticId: string; domainType: string }
  | { kind: 'choosingAction'; semanticId: string; domainType: string }
  | { kind: 'choosingArgument'; actionId: string }
  | { kind: 'confirming'; actionId: string; semanticId?: string };

export interface PBUISessionState {
  selection: { currentObjectId?: string; currentObjectType?: string };
  interaction: PBUIInteractionState;
  commandBuffer: string;
  commandHistory: string[];
  commandHint: string;
  actionResult?: string;
}

export const initialPBUISessionState: PBUISessionState = {
  selection: {},
  interaction: { kind: 'idle' },
  commandBuffer: '',
  commandHistory: [],
  commandHint: '',
};
`
}

func renderSelectors() string {
	return `// Generated by DMETA PBUI React target. Do not edit by hand.
// Presenter logic should compile into selectors/projection functions like these.

export interface PBUIRootStateLike {
  pbui?: unknown;
}

export function selectPBUISession(state: PBUIRootStateLike) {
  return state.pbui;
}

export function projectPresentationRef(input: { id: string; domainType: string; label: string }) {
  return {
    semanticId: input.id,
    domainType: input.domainType,
    presentationType: 'pbui.presentation_ref',
    label: input.label,
  };
}
`
}

func renderActionRequests() string {
	return `// Generated by DMETA PBUI React target. Do not edit by hand.

export interface PBUIActionRequest {
  actionId: string;
  subjectRef?: string;
  arguments?: Record<string, unknown>;
  sourcePresentationType?: string;
}

export function buildPBUIActionRequest(request: PBUIActionRequest): PBUIActionRequest {
  return request;
}
`
}

func renderEventAdapters() string {
	return `// Generated by DMETA PBUI React target. Do not edit by hand.

import type { PBUIActionRequest } from './actionRequests';

export function eventToPBUIActionRequest(actionId: string, subjectRef?: string): PBUIActionRequest {
  return { actionId, subjectRef };
}
`
}

func renderCommandParser() string {
	return `// Generated by DMETA PBUI React target. Do not edit by hand.

export interface ParsedPBUICommand {
  kind: 'empty' | 'action';
  actionId?: string;
  raw: string;
}

export function parsePBUICommand(raw: string): ParsedPBUICommand {
  const trimmed = raw.trim();
  if (!trimmed) return { kind: 'empty', raw };
  return { kind: 'action', actionId: trimmed.split(/\s+/)[0], raw };
}
`
}

func renderPackageReadme(plan ReactPlan) string {
	return fmt.Sprintf("# %s\n\nGenerated PBUI React scaffold plan.\n\nThis package is generated from the DMETA PBUI MetaDesignSystem. It keeps actions,\nobject types, and presentations visible as first-class descriptors so generated\ncomponents can be inspected and traced back to Semantic IR, Interaction IR, and\nPBUI lowering rules.\n\n- MetaDesignSystem: `%s`\n- Target: `%s`\n- Object descriptors: %d\n- Action descriptors: %d\n- Presentation components: %d\n", plan.PackageName, plan.MetaDesignSystem, plan.TargetID, len(plan.ObjectDescriptors), len(plan.ActionDescriptors), len(plan.PresentationPlans))
}

func renderPresenterHook(plan PresentationPlan) string {
	return fmt.Sprintf(`// Generated by DMETA PBUI React target. Do not edit by hand.
// Presenter intent: %s

export interface %sViewModel {
  presentationType: %q;
  semanticId?: string;
  label?: string;
}

export function use%sPresentation(seed: Partial<%sViewModel> = {}): %sViewModel {
  return {
    presentationType: %q,
    ...seed,
  };
}
`, tsComment(plan.PresenterIntent), plan.ComponentName, plan.PresentationTypeID, plan.ComponentName, plan.ComponentName, plan.ComponentName, plan.PresentationTypeID)
}

func renderComponent(plan PresentationPlan) string {
	return fmt.Sprintf(`// Generated by DMETA PBUI React target. Do not edit by hand.
// Presenter intent: %s
// Recognizer intent: %s

export interface %sProps {
  semanticId?: string;
  label?: string;
}

export function %s(props: %sProps) {
  return (
    <section
      data-dmeta-meta-design-system="pbui"
      data-dmeta-codegen-target="react"
      data-dmeta-presentation-type=%q
      data-dmeta-representations=%q
      data-dmeta-actions=%q
    >
      <strong>%s</strong>
      {props.label ? <span>{props.label}</span> : null}
    </section>
  );
}
`, tsComment(plan.PresenterIntent), tsComment(plan.RecognizerIntent), plan.ComponentName, plan.ComponentName, plan.ComponentName, plan.PresentationTypeID, strings.Join(plan.SourceRepresentations, ","), strings.Join(plan.SourceActions, ","), plan.ComponentName)
}

func renderMetadata(provenance ReactFileProvenance) (string, error) {
	b, err := json.MarshalIndent(provenance, "", "  ")
	if err != nil {
		return "", err
	}
	return string(b) + "\n", nil
}

func renderStories(plan PresentationPlan) string {
	return fmt.Sprintf(`// Generated by DMETA PBUI React target. Do not edit by hand.

import type { Meta, StoryObj } from '@storybook/react';
import { %s } from './%s';

const meta = {
  title: 'PBUI/%s',
  component: %s,
  parameters: {
    docs: {
      description: {
        component: %q,
      },
    },
  },
} satisfies Meta<typeof %s>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
    label: %q,
  },
};
`, plan.ComponentName, plan.ComponentName, plan.ComponentName, plan.ComponentName, plan.Rationale, plan.ComponentName, plan.PresentationTypeID)
}

func renderBarrel(symbol string) string {
	return fmt.Sprintf("export * from './%s';\n", filepath.Base(symbol))
}

func tsComment(value string) string {
	return strings.ReplaceAll(value, "\n", " ")
}
