package react

import (
	"bytes"
	"encoding/json"
	"fmt"
	"path/filepath"
	"strings"

	genmeta "github.com/go-go-golems/dmeta/pkg/dmeta/generator/metadata"
)

const generatedHeader = "// Code generated by dmeta scaffold-react from Web MetaDesignSystem obligations. DO NOT EDIT until promoted.\n\n"

type GeneratedFile struct {
	Path    string
	Kind    string
	Content []byte
}

type MetadataSidecar struct {
	GeneratedBy      string             `json:"generatedBy"`
	MetaDesignSystem string             `json:"metaDesignSystem"`
	CodegenTarget    string             `json:"codegenTarget"`
	ComponentName    string             `json:"componentName"`
	TemplateID       string             `json:"templateId"`
	Variant          string             `json:"variant,omitempty"`
	Realizes         RealizesMetadata   `json:"realizes"`
	Web              WebMetadata        `json:"web"`
	React            ReactMetadata      `json:"react"`
	Provenance       ProvenanceMetadata `json:"provenance"`
}

type RealizesMetadata struct {
	Representations []string `json:"representations,omitempty"`
	Actions         []string `json:"actions,omitempty"`
}

type WebMetadata struct {
	Slots         []string `json:"slots,omitempty"`
	VisualStates  []string `json:"visualStates,omitempty"`
	EventBindings []string `json:"eventBindings,omitempty"`
}

type ReactMetadata struct {
	PackageName string         `json:"packageName,omitempty"`
	Files       []ReactFileRef `json:"files,omitempty"`
}

type ReactFileRef struct {
	Kind   string `json:"kind"`
	Path   string `json:"path"`
	Symbol string `json:"symbol,omitempty"`
}

type ProvenanceMetadata struct {
	DomainTypes []string `json:"domainTypes,omitempty"`
	SourceRules []string `json:"sourceRules,omitempty"`
	Passes      []string `json:"passes,omitempty"`
}

func Generate(plan ScaffoldPlan) ([]GeneratedFile, error) {
	files := make([]GeneratedFile, 0, len(plan.Files)+len(plan.Components)*8)
	for _, file := range plan.Files {
		content, err := renderPackageFile(plan, file)
		if err != nil {
			return nil, err
		}
		files = append(files, GeneratedFile{Path: file.Path, Kind: file.Kind, Content: content})
	}
	for _, component := range plan.Components {
		for _, file := range component.Files {
			content, err := renderComponentFile(plan, component, file)
			if err != nil {
				return nil, err
			}
			files = append(files, GeneratedFile{Path: file.Path, Kind: file.Kind, Content: content})
		}
	}
	return files, nil
}

func RenderMetadataSidecar(plan ScaffoldPlan, component ComponentPlan) ([]byte, error) {
	metadata := webGeneratedMetadata(plan, component, PlannedFile{Path: filepath.Join(component.OutputDir, component.ComponentName, component.ComponentName+".metadata.json"), Kind: "metadata", Symbol: component.ComponentName + "Metadata"})
	return genmeta.RenderJSON(metadata)
}

func legacyMetadataSidecar(component ComponentPlan) MetadataSidecar {
	return MetadataSidecar{
		GeneratedBy:      "dmeta scaffold-react",
		MetaDesignSystem: "web",
		CodegenTarget:    "react",
		ComponentName:    component.ComponentName,
		TemplateID:       component.TemplateID,
		Variant:          component.Variant,
		Realizes: RealizesMetadata{
			Representations: append([]string{}, component.RealizesRepresentations...),
			Actions:         append([]string{}, component.RealizesActions...),
		},
		Web: WebMetadata{
			Slots:         append([]string{}, component.Slots...),
			VisualStates:  append([]string{}, component.VisualStates...),
			EventBindings: append([]string{}, component.EventBindings...),
		},
		React: ReactMetadata{
			PackageName: component.PackageName,
			Files:       reactFileRefs(component.Files),
		},
		Provenance: ProvenanceMetadata{
			DomainTypes: append([]string{}, component.SourceDomainTypes...),
			SourceRules: append([]string{}, component.SourceRules...),
			Passes:      passesFromComponent(component),
		},
	}
}

func GenerateMetadataSidecars(plan ScaffoldPlan) ([]GeneratedFile, error) {
	files := make([]GeneratedFile, 0, len(plan.Components))
	for _, component := range plan.Components {
		content, err := RenderMetadataSidecar(plan, component)
		if err != nil {
			return nil, err
		}
		files = append(files, GeneratedFile{Path: filepath.Join(component.OutputDir, component.ComponentName, component.ComponentName+".metadata.json"), Kind: "metadata", Content: content})
	}
	return files, nil
}

func renderPackageFile(plan ScaffoldPlan, file PlannedFile) ([]byte, error) {
	if file.Kind != "package_index" {
		return nil, fmt.Errorf("unsupported package file kind %q", file.Kind)
	}
	var b bytes.Buffer
	b.WriteString(generatedHeader)
	b.WriteString(fmt.Sprintf("// Instance: %s\n", plan.InstanceID))
	b.WriteString(fmt.Sprintf("// MetaDesignSystem: %s\n", plan.MetaDesignSystem))
	b.WriteString(fmt.Sprintf("// Target: %s\n\n", plan.TargetID))
	for _, component := range plan.Components {
		b.WriteString(fmt.Sprintf("export * from \"./%s\";\n", component.ComponentName))
	}
	return b.Bytes(), nil
}

func renderComponentFile(plan ScaffoldPlan, component ComponentPlan, file PlannedFile) ([]byte, error) {
	switch file.Kind {
	case "component":
		return []byte(renderComponent(plan, component, file)), nil
	case "types":
		return []byte(renderTypes(plan, component, file)), nil
	case "metadata":
		content, err := RenderMetadataSidecar(plan, component)
		if err != nil {
			return nil, err
		}
		return content, nil
	case "stories":
		return []byte(renderStories(plan, component, file)), nil
	case "style":
		return []byte(renderStyles(component)), nil
	case "barrel":
		return []byte(renderBarrel(plan, component, file)), nil
	case "adapter_todo":
		return []byte(renderAdapterTODO(plan, component, file)), nil
	case "readme":
		return []byte(renderReadme(component)), nil
	default:
		return nil, fmt.Errorf("unsupported React file kind %q", file.Kind)
	}
}

func renderTypes(plan ScaffoldPlan, component ComponentPlan, file PlannedFile) string {
	var b bytes.Buffer
	b.WriteString(webTypeScriptPrelude(plan, component, file))
	b.WriteString(fmt.Sprintf("export type %sSlotName =\n", component.ComponentName))
	if len(component.Slots) == 0 {
		b.WriteString("  never;\n")
	} else {
		for _, slot := range component.Slots {
			b.WriteString(fmt.Sprintf("  | %q\n", slot))
		}
		b.WriteString(";\n")
	}
	b.WriteString("\n")
	b.WriteString(fmt.Sprintf("export type %sVisualState =\n", component.ComponentName))
	if len(component.VisualStates) == 0 {
		b.WriteString("  | \"default\"\n")
		b.WriteString(";\n")
	} else {
		for _, state := range component.VisualStates {
			b.WriteString(fmt.Sprintf("  | %q\n", state))
		}
		b.WriteString(";\n")
	}
	b.WriteString("\n")
	b.WriteString(fmt.Sprintf("export type %sProps = {\n", component.ComponentName))
	b.WriteString("  className?: string;\n")
	b.WriteString(fmt.Sprintf("  visualState?: %sVisualState;\n", component.ComponentName))
	b.WriteString("  slots?: Partial<Record<")
	b.WriteString(component.ComponentName)
	b.WriteString("SlotName, unknown>>;\n")
	for _, eventBinding := range component.EventBindings {
		b.WriteString(fmt.Sprintf("  %s?: (payload: unknown) => void;\n", callbackName(eventBinding)))
	}
	b.WriteString("};\n")
	return b.String()
}

func renderComponent(plan ScaffoldPlan, component ComponentPlan, file PlannedFile) string {
	return fmt.Sprintf(`%simport styles from "./%s.module.css";
import type { %sProps, %sSlotName } from "./%s.types";

/**
 * %s
 *
 * React target scaffold for Web template %s.
 * MetaDesignSystem: web.
 * Realizes representations: %s.
 * Realizes actions: %s.
 */
export function %s(props: %sProps) {
  const { className, visualState = %q, slots = {} } = props;
  const rootClassName = [styles.root, className].filter(Boolean).join(" ");

  return (
    <section
      className={rootClassName}
      data-dmeta-meta-design-system="web"
      data-dmeta-codegen-target="react"
      data-dmeta-widget-template=%q
      data-dmeta-representations=%q
      data-dmeta-actions=%q
      data-dmeta-visual-state={visualState}
    >
      <header className={styles.header}>
        <strong>%s</strong>
        <span>{visualState}</span>
      </header>
      <dl className={styles.slots}>
        {(%s as %sSlotName[]).map((slotName) => (
          <div key={slotName} className={styles.slot} data-dmeta-slot={slotName}>
            <dt>{slotName}</dt>
            <dd>{String(slots[slotName] ?? "")}</dd>
          </div>
        ))}
      </dl>
    </section>
  );
}

export default %s;
`, webTypeScriptPrelude(plan, component, file), component.ComponentName, component.ComponentName, component.ComponentName, component.ComponentName, component.ComponentName, component.TemplateID, strings.Join(component.RealizesRepresentations, ", "), strings.Join(component.RealizesActions, ", "), component.ComponentName, component.ComponentName, defaultVisualState(component), component.TemplateID, strings.Join(component.RealizesRepresentations, ","), strings.Join(component.RealizesActions, ","), component.ComponentName, tsStringArray(component.Slots), component.ComponentName, component.ComponentName)
}

func renderStories(plan ScaffoldPlan, component ComponentPlan, file PlannedFile) string {
	return fmt.Sprintf(`%simport type { Meta, StoryObj } from "@storybook/react";
import { %s } from "./%s";

const meta = {
  title: "Generated React/%s",
  component: %s,
  parameters: {
    docs: {
      description: {
        component: %s,
      },
    },
  },
} satisfies Meta<typeof %s>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
    visualState: %q,
    slots: {},
  },
};
`, webTypeScriptPrelude(plan, component, file), component.ComponentName, component.ComponentName, component.ComponentName, component.ComponentName, tsString(storyDescription(component)), component.ComponentName, defaultVisualState(component))
}

func renderStyles(_ ComponentPlan) string {
	return fmt.Sprintf(`%s.root {
  display: block;
  border: 1px solid currentColor;
  border-radius: 12px;
  padding: 12px;
}

.header {
  display: flex;
  justify-content: space-between;
  gap: 8px;
}

.slots {
  display: grid;
  gap: 8px;
  margin: 12px 0 0;
}

.slot {
  display: grid;
  gap: 2px;
}
`, cssGeneratedHeader())
}

func renderBarrel(_ ScaffoldPlan, component ComponentPlan, _ PlannedFile) string {
	return fmt.Sprintf(`%sexport { %s } from "./%s";
export type { %sProps, %sSlotName, %sVisualState } from "./%s.types";
`, generatedHeader, component.ComponentName, component.ComponentName, component.ComponentName, component.ComponentName, component.ComponentName, component.ComponentName)
}

func renderAdapterTODO(plan ScaffoldPlan, component ComponentPlan, file PlannedFile) string {
	var b bytes.Buffer
	b.WriteString(webTypeScriptPrelude(plan, component, file))
	b.WriteString(fmt.Sprintf("import type { %sProps } from \"./%s.types\";\n\n", component.ComponentName, component.ComponentName))
	b.WriteString(fmt.Sprintf("export function adapt%sProps(input: unknown): %sProps {\n", component.ComponentName, component.ComponentName))
	b.WriteString("  // TODO: Map concrete app data into the React target props.\n")
	b.WriteString(fmt.Sprintf("  // Web slots: %s\n", commaList(component.Slots)))
	b.WriteString(fmt.Sprintf("  // Event bindings: %s\n", commaList(component.EventBindings)))
	b.WriteString("  void input;\n")
	b.WriteString("  return { slots: {} };\n")
	b.WriteString("}\n")
	return b.String()
}

func renderReadme(component ComponentPlan) string {
	return fmt.Sprintf(`# %s

Generated React scaffold plan for %s.

- MetaDesignSystem: web
- Target: react
- Variant: %s
- Representations: %s
- Actions: %s
- Domain types: %s
- Source Web lowering rules: %s

Promote and edit intentionally. Do not blindly regenerate over maintained code.
`, component.ComponentName, component.TemplateID, component.Variant, commaList(component.RealizesRepresentations), commaList(component.RealizesActions), commaList(component.SourceDomainTypes), commaList(component.SourceRules))
}

func reactFileRefs(files []PlannedFile) []ReactFileRef {
	refs := make([]ReactFileRef, 0, len(files))
	for _, file := range files {
		refs = append(refs, ReactFileRef{Kind: file.Kind, Path: file.Path, Symbol: file.Symbol})
	}
	return refs
}

func commaList(values []string) string {
	if len(values) == 0 {
		return "none"
	}
	return strings.Join(values, ", ")
}

func passesFromComponent(component ComponentPlan) []string {
	for _, file := range component.Files {
		if len(file.Provenance.Passes) > 0 {
			return append([]string{}, file.Provenance.Passes...)
		}
	}
	return nil
}

func callbackName(action string) string {
	parts := strings.FieldsFunc(action, func(r rune) bool { return r == '_' || r == '-' || r == '.' })
	for i, part := range parts {
		if part == "" {
			continue
		}
		parts[i] = strings.ToUpper(part[:1]) + part[1:]
	}
	return "on" + strings.Join(parts, "")
}

func defaultVisualState(component ComponentPlan) string {
	if len(component.VisualStates) == 0 {
		return "default"
	}
	return component.VisualStates[0]
}

func tsStringArray(values []string) string {
	quoted := make([]string, 0, len(values))
	for _, value := range values {
		quoted = append(quoted, tsString(value))
	}
	return "[" + strings.Join(quoted, ", ") + "]"
}

func storyDescription(component ComponentPlan) string {
	parts := []string{
		fmt.Sprintf("Generated React scaffold for Web template %s.", component.TemplateID),
		"MetaDesignSystem: web.",
	}
	if len(component.RealizesRepresentations) > 0 {
		parts = append(parts, "Representations: "+strings.Join(component.RealizesRepresentations, ", ")+".")
	}
	if len(component.RealizesActions) > 0 {
		parts = append(parts, "Actions: "+strings.Join(component.RealizesActions, ", ")+".")
	}
	return strings.Join(parts, " ")
}

func tsString(value string) string {
	b, _ := json.Marshal(value)
	return string(b)
}

func cssGeneratedHeader() string {
	return "/* Code generated by dmeta scaffold-react from Web MetaDesignSystem obligations. DO NOT EDIT until promoted. */\n\n"
}

func webTypeScriptPrelude(plan ScaffoldPlan, component ComponentPlan, file PlannedFile) string {
	prelude, err := genmeta.RenderTypeScriptPrelude(webGeneratedMetadata(plan, component, file))
	if err != nil {
		return generatedHeader
	}
	return prelude
}

func webGeneratedMetadata(plan ScaffoldPlan, component ComponentPlan, file PlannedFile) genmeta.GeneratedFileMetadata {
	generated := plan.Generated
	if generated.By == "" {
		generated.By = "dmeta scaffold-react"
	}
	meta := genmeta.GeneratedFileMetadata{
		Generated: generated,
		Artifact: genmeta.ArtifactInfo{
			Path:       file.Path,
			Kind:       file.Kind,
			Language:   reactLanguageForPath(file.Path),
			Symbol:     file.Symbol,
			Promotable: webFileIsPromotable(file.Kind),
		},
		Pipeline: genmeta.PipelineInfo{
			SemanticRoot:     plan.SemanticRoot,
			InteractionsRoot: plan.InteractionsRoot,
			MetaDesignSystem: "web",
			Target:           plan.TargetID,
			Passes:           passesFromComponent(component),
		},
		Sources: []genmeta.SourceReference{
			{Path: plan.SemanticRoot, Role: "semantic package", Why: "Provides domain types, archetypes, capabilities, and examples used by Web lowering."},
			{Path: plan.InteractionsRoot, Role: "interaction package", Why: "Provides action and representation obligations lowered into Web widget obligations."},
			{Path: plan.WebRoot, Role: "Web MetaDesignSystem", Why: "Provides widget templates, Web lowering rules, and target-independent web obligations."},
			{Path: plan.TargetFile, Role: "React target", Why: "Provides React target defaults and file kinds for this scaffold."},
		},
		Semantics: &genmeta.SemanticGuidance{
			DomainTypes:     append([]string{}, component.SourceDomainTypes...),
			Representations: append([]string{}, component.RealizesRepresentations...),
			Actions:         append([]string{}, component.RealizesActions...),
			SourceRules:     append([]string{}, component.SourceRules...),
		},
		Web: &genmeta.WebGuidance{
			TemplateID:    component.TemplateID,
			Variant:       component.Variant,
			Slots:         append([]string{}, component.Slots...),
			VisualStates:  append([]string{}, component.VisualStates...),
			EventBindings: append([]string{}, component.EventBindings...),
		},
		React: &genmeta.ReactGuidance{
			PackageName: component.PackageName,
			Files:       generatedReactFileRefs(component.Files),
		},
		Guidance: &genmeta.HumanGuidance{
			Summary: "Generated Web React scaffold. Promote intentionally before hand editing and keep metadata visible to maintain Semantic IR and Web MetaDesignSystem context.",
			ImplementationNotes: []string{
				"Use dmetaGeneratedMetadata to trace props, slots, visual states, and event bindings back to Web lowering obligations.",
				"When promoted, append human changes to the promotion changelog before modifying behavior or styling.",
			},
		},
	}
	return genmeta.WithDefaults(meta)
}

func generatedReactFileRefs(files []PlannedFile) []genmeta.FileRef {
	refs := make([]genmeta.FileRef, 0, len(files))
	for _, file := range files {
		refs = append(refs, genmeta.FileRef{Kind: file.Kind, Path: file.Path, Symbol: file.Symbol})
	}
	return refs
}

func webFileIsPromotable(kind string) bool {
	switch kind {
	case "component", "types", "stories", "style", "adapter_todo", "readme", "barrel":
		return true
	default:
		return false
	}
}

func reactLanguageForPath(path string) string {
	switch filepath.Ext(path) {
	case ".tsx":
		return "tsx"
	case ".ts":
		return "ts"
	case ".json":
		return "json"
	case ".css":
		return "css"
	case ".md":
		return "markdown"
	default:
		return "text"
	}
}
