package react

import (
	"bytes"
	"encoding/json"
	"fmt"
	"path/filepath"
	"sort"
	"strings"

	genmeta "github.com/go-go-golems/dmeta/pkg/dmeta/generator/metadata"
	"github.com/go-go-golems/dmeta/pkg/dmeta/validator"
)

const generatedHeader = "// Code generated by dmeta scaffold-react from Web MetaDesignSystem obligations. DO NOT EDIT generated files directly.\n\n"

type GeneratedFile struct {
	Path    string
	Kind    string
	Content []byte
}

type MetadataSidecar struct {
	GeneratedBy      string             `json:"generatedBy"`
	MetaDesignSystem string             `json:"metaDesignSystem"`
	CodegenTarget    string             `json:"codegenTarget"`
	ComponentName    string             `json:"componentName"`
	TemplateID       string             `json:"templateId"`
	Variant          string             `json:"variant,omitempty"`
	Realizes         RealizesMetadata   `json:"realizes"`
	Web              WebMetadata        `json:"web"`
	React            ReactMetadata      `json:"react"`
	Provenance       ProvenanceMetadata `json:"provenance"`
}

type RealizesMetadata struct {
	Representations []string `json:"representations,omitempty"`
	Actions         []string `json:"actions,omitempty"`
}

type WebMetadata struct {
	Slots         []string `json:"slots,omitempty"`
	VisualStates  []string `json:"visualStates,omitempty"`
	EventBindings []string `json:"eventBindings,omitempty"`
}

type ReactMetadata struct {
	PackageName string         `json:"packageName,omitempty"`
	Files       []ReactFileRef `json:"files,omitempty"`
}

type ReactFileRef struct {
	Kind   string `json:"kind"`
	Path   string `json:"path"`
	Symbol string `json:"symbol,omitempty"`
}

type ProvenanceMetadata struct {
	DomainTypes []string `json:"domainTypes,omitempty"`
	SourceRules []string `json:"sourceRules,omitempty"`
	Passes      []string `json:"passes,omitempty"`
}

func Generate(plan ScaffoldPlan) ([]GeneratedFile, error) {
	files := make([]GeneratedFile, 0, len(plan.Files)+len(plan.Components)*8)
	for _, file := range plan.Files {
		content, err := renderPackageFile(plan, file)
		if err != nil {
			return nil, err
		}
		files = append(files, GeneratedFile{Path: file.Path, Kind: file.Kind, Content: content})
	}
	for _, component := range plan.Components {
		for _, file := range component.Files {
			content, err := renderComponentFile(plan, component, file)
			if err != nil {
				return nil, err
			}
			files = append(files, GeneratedFile{Path: file.Path, Kind: file.Kind, Content: content})
		}
	}
	return files, nil
}

func RenderMetadataSidecar(plan ScaffoldPlan, component ComponentPlan) ([]byte, error) {
	metadata := webGeneratedMetadata(plan, component, PlannedFile{Path: filepath.Join(component.ComponentDir, metadataFileName(component)), Kind: "metadata", Symbol: component.ComponentName + "Metadata"})
	return genmeta.RenderJSON(metadata)
}

func legacyMetadataSidecar(component ComponentPlan) MetadataSidecar {
	return MetadataSidecar{
		GeneratedBy:      "dmeta scaffold-react",
		MetaDesignSystem: "web",
		CodegenTarget:    "react",
		ComponentName:    component.ComponentName,
		TemplateID:       component.TemplateID,
		Variant:          component.Variant,
		Realizes: RealizesMetadata{
			Representations: append([]string{}, component.RealizesRepresentations...),
			Actions:         append([]string{}, component.RealizesActions...),
		},
		Web: WebMetadata{
			Slots:         append([]string{}, component.Slots...),
			VisualStates:  append([]string{}, component.VisualStates...),
			EventBindings: append([]string{}, component.EventBindings...),
		},
		React: ReactMetadata{
			PackageName: component.PackageName,
			Files:       reactFileRefs(component.Files),
		},
		Provenance: ProvenanceMetadata{
			DomainTypes: append([]string{}, component.SourceDomainTypes...),
			SourceRules: append([]string{}, component.SourceRules...),
			Passes:      passesFromComponent(component),
		},
	}
}

func GenerateMetadataSidecars(plan ScaffoldPlan) ([]GeneratedFile, error) {
	files := make([]GeneratedFile, 0, len(plan.Components))
	for _, component := range plan.Components {
		content, err := RenderMetadataSidecar(plan, component)
		if err != nil {
			return nil, err
		}
		files = append(files, GeneratedFile{Path: filepath.Join(component.ComponentDir, metadataFileName(component)), Kind: "metadata", Content: content})
	}
	return files, nil
}

func renderPackageFile(plan ScaffoldPlan, file PlannedFile) ([]byte, error) {
	if file.Kind != "package_index" {
		return nil, fmt.Errorf("unsupported package file kind %q", file.Kind)
	}
	var b bytes.Buffer
	b.WriteString(generatedHeader)
	b.WriteString(fmt.Sprintf("// Instance: %s\n", plan.InstanceID))
	b.WriteString(fmt.Sprintf("// MetaDesignSystem: %s\n", plan.MetaDesignSystem))
	b.WriteString(fmt.Sprintf("// Target: %s\n\n", plan.TargetID))
	for _, component := range plan.Components {
		b.WriteString(fmt.Sprintf("export * from \"%s\";\n", component.PackageExportPath))
	}
	return b.Bytes(), nil
}

func renderComponentFile(plan ScaffoldPlan, component ComponentPlan, file PlannedFile) ([]byte, error) {
	switch file.Kind {
	case "component":
		return []byte(renderComponent(plan, component, file)), nil
	case "types":
		return []byte(renderTypes(plan, component, file)), nil
	case "metadata":
		content, err := RenderMetadataSidecar(plan, component)
		if err != nil {
			return nil, err
		}
		return content, nil
	case "stories":
		return []byte(renderStories(plan, component, file)), nil
	case "style":
		return []byte(renderStyles(component)), nil
	case "barrel":
		return []byte(renderBarrel(plan, component, file)), nil
	case "adapter_todo":
		return []byte(renderAdapterTODO(plan, component, file)), nil
	case "readme":
		return []byte(renderReadme(component)), nil
	default:
		return nil, fmt.Errorf("unsupported React file kind %q", file.Kind)
	}
}

func renderTypes(plan ScaffoldPlan, component ComponentPlan, file PlannedFile) string {
	var b bytes.Buffer
	b.WriteString(webTypeScriptPrelude(plan, component, file))
	b.WriteString(fmt.Sprintf("export type %sSlotName =\n", component.ComponentName))
	if len(component.Slots) == 0 {
		b.WriteString("  never;\n")
	} else {
		for _, slot := range component.Slots {
			b.WriteString(fmt.Sprintf("  | %q\n", slot))
		}
		b.WriteString(";\n")
	}
	b.WriteString("\n")
	b.WriteString(fmt.Sprintf("export type %sVisualState =\n", component.ComponentName))
	if len(component.VisualStates) == 0 {
		b.WriteString("  | \"default\"\n")
		b.WriteString(";\n")
	} else {
		for _, state := range component.VisualStates {
			b.WriteString(fmt.Sprintf("  | %q\n", state))
		}
		b.WriteString(";\n")
	}
	b.WriteString("\n")
	b.WriteString(fmt.Sprintf("export type %sProps = {\n", component.ComponentName))
	b.WriteString("  className?: string;\n")
	b.WriteString(fmt.Sprintf("  visualState?: %sVisualState;\n", component.ComponentName))
	b.WriteString("  slots?: Partial<Record<")
	b.WriteString(component.ComponentName)
	b.WriteString("SlotName, unknown>>;\n")
	b.WriteString(renderContractProps(component))
	for _, eventBinding := range component.EventBindings {
		b.WriteString(fmt.Sprintf("  %s?: (payload: unknown) => void;\n", callbackName(eventBinding)))
	}
	for _, eventName := range sortedEventNames(component.Template.Contract.Events) {
		b.WriteString(fmt.Sprintf("  %s%s: (payload: %s) => void;\n", eventName, optionalSuffix(!component.Template.Contract.Events[eventName].Required), tsTypeFromContractType(component.Template.Contract.Events[eventName].PayloadType)))
	}
	b.WriteString("};\n")
	return b.String()
}

func renderComponent(plan ScaffoldPlan, component ComponentPlan, file PlannedFile) string {
	return fmt.Sprintf(`%simport styles from "./%s.module.css";
import type { %sProps, %sSlotName } from "./%s.types";

/**
 * %s
 *
 * React target scaffold for Web template %s.
 * MetaDesignSystem: web.
 * Component kind: %s.
 * Component specificity: %s.
 * Component role: %s.
 * Realizes representations: %s.
 * Realizes actions: %s.
 */
export function %s(props: %sProps) {
  const { className, visualState = %q, slots = {} } = props;
  const rootClassName = [styles.root, className].filter(Boolean).join(" ");

  return (
    <section
      className={rootClassName}
      data-dmeta-meta-design-system="web"
      data-dmeta-codegen-target="react"
      data-dmeta-widget-template=%q
      data-dmeta-representations=%q
      data-dmeta-actions=%q
      data-dmeta-visual-state={visualState}
    >
      <header className={styles.header}>
        <strong>%s</strong>
        <span>{visualState}</span>
      </header>
      <dl className={styles.slots}>
        {(%s as %sSlotName[]).map((slotName) => (
          <div key={slotName} className={styles.slot} data-dmeta-slot={slotName}>
            <dt>{slotName}</dt>
            <dd>{String(slots[slotName] ?? "")}</dd>
          </div>
        ))}
      </dl>
    </section>
  );
}

export default %s;
`, webTypeScriptPrelude(plan, component, file), templateFileBase(component), component.ComponentName, component.ComponentName, templateFileBase(component), component.ComponentName, component.TemplateID, component.ComponentKind, component.ComponentSpecificity, component.ComponentRole, strings.Join(component.RealizesRepresentations, ", "), strings.Join(component.RealizesActions, ", "), component.ComponentName, component.ComponentName, defaultVisualState(component), component.TemplateID, strings.Join(component.RealizesRepresentations, ","), strings.Join(component.RealizesActions, ","), component.ComponentName, tsStringArray(component.Slots), component.ComponentName, component.ComponentName)
}

func renderStories(plan ScaffoldPlan, component ComponentPlan, file PlannedFile) string {
	return fmt.Sprintf(`%simport type { Meta, StoryObj } from "@storybook/react";
import { %s } from "./%s";

const meta = {
  title: "Generated React/%s/%s",
  component: %s,
  parameters: {
    docs: {
      description: {
        component: %s,
      },
    },
  },
} satisfies Meta<typeof %s>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
    visualState: %q,
    slots: {},
%s  },
};
`, webTypeScriptPrelude(plan, component, file), component.ComponentName, templateFileBase(component), storybookKind(component), component.ComponentName, component.ComponentName, tsString(storyDescription(component)), component.ComponentName, defaultVisualState(component), sampleStoryArgs(component))
}

func renderStyles(component ComponentPlan) string {
	return fmt.Sprintf(`%s.root {
  display: block;
  border: 1px solid currentColor;
  border-radius: 12px;
  padding: 12px;
}

.header {
  display: flex;
  justify-content: space-between;
  gap: 8px;
}

.slots {
  display: grid;
  gap: 8px;
  margin: 12px 0 0;
}

.slot {
  display: grid;
  gap: 2px;
}
`, cssGeneratedHeader(component))
}

func renderBarrel(_ ScaffoldPlan, component ComponentPlan, file PlannedFile) string {
	return fmt.Sprintf(`%sexport { %s } from "./%s";
export type { %sProps, %sSlotName, %sVisualState } from "./%s.types";
`, webTypeScriptPrelude(ScaffoldPlan{}, component, file), component.ComponentName, templateFileBase(component), component.ComponentName, component.ComponentName, component.ComponentName, templateFileBase(component))
}

func renderAdapterTODO(plan ScaffoldPlan, component ComponentPlan, file PlannedFile) string {
	var b bytes.Buffer
	b.WriteString(webTypeScriptPrelude(plan, component, file))
	b.WriteString(fmt.Sprintf("import type { %sProps } from \"./%s.types\";\n\n", component.ComponentName, templateFileBase(component)))
	b.WriteString(fmt.Sprintf("export function adapt%sProps(input: unknown): %sProps {\n", component.ComponentName, component.ComponentName))
	b.WriteString("  // TODO: Map concrete app data into the React target props.\n")
	b.WriteString(fmt.Sprintf("  // Component kind: %s\n", component.ComponentKind))
	b.WriteString(fmt.Sprintf("  // Web slots: %s\n", commaList(component.Slots)))
	b.WriteString(fmt.Sprintf("  // Event bindings: %s\n", commaList(component.EventBindings)))
	b.WriteString(fmt.Sprintf("  // Contract props: %s\n", commaList(sortedPropNames(component.Template.Contract.Props))))
	b.WriteString("  void input;\n")
	b.WriteString("  return {\n")
	b.WriteString("    slots: {},\n")
	b.WriteString(sampleStoryArgs(component))
	b.WriteString("  };\n")
	b.WriteString("}\n")
	return b.String()
}

func renderReadme(component ComponentPlan) string {
	return fmt.Sprintf(`# %s

Generated React scaffold plan for %s.

- MetaDesignSystem: web
- Target: react
- Variant: %s
- Component kind: %s
- Specificity: %s
- Family: %s
- Role: %s
- Lifecycle: %s
- Representations: %s
- Actions: %s
- Domain types: %s
- Source Web lowering rules: %s

Promote and edit intentionally. Do not blindly regenerate over maintained code.
`, component.ComponentName, component.TemplateID, component.Variant, component.ComponentKind, component.ComponentSpecificity, component.ComponentFamily, component.ComponentRole, component.ComponentLifecycle, commaList(component.RealizesRepresentations), commaList(component.RealizesActions), commaList(component.SourceDomainTypes), commaList(component.SourceRules))
}

func reactFileRefs(files []PlannedFile) []ReactFileRef {
	refs := make([]ReactFileRef, 0, len(files))
	for _, file := range files {
		refs = append(refs, ReactFileRef{Kind: file.Kind, Path: file.Path, Symbol: file.Symbol})
	}
	return refs
}

func commaList(values []string) string {
	if len(values) == 0 {
		return "none"
	}
	return strings.Join(values, ", ")
}

func sampleStoryArgs(component ComponentPlan) string {
	if len(component.Template.Contract.Props) == 0 && len(component.Template.Contract.Events) == 0 {
		return ""
	}
	var b strings.Builder
	for _, propName := range sortedPropNames(component.Template.Contract.Props) {
		contract := component.Template.Contract.Props[propName]
		if strings.HasSuffix(propName, "Props") {
			for _, fieldName := range sortedFieldNames(contract.Fields) {
				field := contract.Fields[fieldName]
				if !field.Required {
					continue
				}
				b.WriteString(fmt.Sprintf("    %s: %s,\n", fieldName, sampleValueForPropField(field, fieldName)))
			}
			continue
		}
		if !contract.Required {
			continue
		}
		b.WriteString(fmt.Sprintf("    %s: {\n", propName))
		for _, fieldName := range sortedFieldNames(contract.Fields) {
			field := contract.Fields[fieldName]
			if !field.Required {
				continue
			}
			b.WriteString(fmt.Sprintf("      %s: %s,\n", fieldName, sampleValueForPropField(field, fieldName)))
		}
		b.WriteString("    },\n")
	}
	for _, eventName := range sortedEventNames(component.Template.Contract.Events) {
		event := component.Template.Contract.Events[eventName]
		if event.Required {
			b.WriteString(fmt.Sprintf("    %s: () => undefined,\n", eventName))
		}
	}
	return b.String()
}

func sampleValueForPropField(field validator.PropField, fieldName string) string {
	if len(field.Values) > 0 {
		return tsString(field.Values[0])
	}
	switch tsTypeFromPropField(field) {
	case "string":
		return tsString(sampleStringForField(fieldName))
	case "number":
		return "0"
	case "boolean":
		return "false"
	default:
		if strings.EqualFold(field.TypeRef, "ReactNode") || strings.EqualFold(field.Type, "ReactNode") {
			return tsString(sampleStringForField(fieldName))
		}
		if strings.HasSuffix(tsTypeFromPropField(field), "[]") {
			return "[]"
		}
		return "undefined"
	}
}

func sampleStringForField(fieldName string) string {
	switch strings.ToLower(fieldName) {
	case "children", "label", "title", "name":
		return "Sample"
	case "id":
		return "sample-id"
	default:
		return "Sample"
	}
}

func renderContractProps(component ComponentPlan) string {
	if len(component.Template.Contract.Props) == 0 {
		return ""
	}
	var b strings.Builder
	for _, propName := range sortedPropNames(component.Template.Contract.Props) {
		contract := component.Template.Contract.Props[propName]
		if strings.HasSuffix(propName, "Props") {
			for _, fieldName := range sortedFieldNames(contract.Fields) {
				field := contract.Fields[fieldName]
				b.WriteString(renderPropComment(field, "  "))
				b.WriteString(fmt.Sprintf("  %s%s: %s;\n", fieldName, optionalSuffix(!field.Required), tsTypeFromPropField(field)))
			}
			continue
		}
		b.WriteString(renderInterfaceComment(contract, "  "))
		b.WriteString(fmt.Sprintf("  %s%s: {\n", propName, optionalSuffix(!contract.Required)))
		for _, fieldName := range sortedFieldNames(contract.Fields) {
			field := contract.Fields[fieldName]
			b.WriteString(renderPropComment(field, "    "))
			b.WriteString(fmt.Sprintf("    %s%s: %s;\n", fieldName, optionalSuffix(!field.Required), tsTypeFromPropField(field)))
		}
		b.WriteString("  };\n")
	}
	return b.String()
}

func renderInterfaceComment(contract validator.InterfaceContract, indent string) string {
	parts := []string{}
	if contract.Source != "" {
		parts = append(parts, "source: "+contract.Source)
	}
	if contract.SourceRef != "" {
		parts = append(parts, "source_ref: "+contract.SourceRef)
	}
	if contract.Description != "" {
		parts = append(parts, contract.Description)
	}
	if len(parts) == 0 {
		return ""
	}
	return indent + "/** " + strings.Join(parts, "; ") + " */\n"
}

func renderPropComment(field validator.PropField, indent string) string {
	parts := []string{}
	if field.Source != "" {
		parts = append(parts, "source: "+field.Source)
	}
	if field.SourceRef != "" {
		parts = append(parts, "source_ref: "+field.SourceRef)
	}
	if field.Description != "" {
		parts = append(parts, field.Description)
	}
	if len(parts) == 0 {
		return ""
	}
	return indent + "/** " + strings.Join(parts, "; ") + " */\n"
}

func sortedPropNames(props map[string]validator.InterfaceContract) []string {
	names := make([]string, 0, len(props))
	for name := range props {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

func sortedFieldNames(fields map[string]validator.PropField) []string {
	names := make([]string, 0, len(fields))
	for name := range fields {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

func sortedEventNames(events map[string]validator.EventContract) []string {
	names := make([]string, 0, len(events))
	for name := range events {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

func optionalSuffix(optional bool) string {
	if optional {
		return "?"
	}
	return ""
}

func tsTypeFromPropField(field validator.PropField) string {
	if len(field.Values) > 0 {
		values := make([]string, 0, len(field.Values))
		for _, value := range field.Values {
			values = append(values, tsString(value))
		}
		return strings.Join(values, " | ")
	}
	if field.ItemTypeRef != "" {
		return tsTypeFromContractType(field.ItemTypeRef) + "[]"
	}
	if field.TypeRef != "" {
		return tsTypeFromContractType(field.TypeRef)
	}
	return tsTypeFromContractType(field.Type)
}

func tsTypeFromContractType(contractType string) string {
	t := strings.TrimSpace(contractType)
	if t == "" {
		return "unknown"
	}
	if strings.HasSuffix(t, "[]") {
		return tsTypeFromContractType(strings.TrimSuffix(t, "[]")) + "[]"
	}
	switch t {
	case "string", "number", "boolean", "unknown", "any", "void":
		return t
	case "integer", "float", "double":
		return "number"
	default:
		return "unknown"
	}
}

func storybookKind(component ComponentPlan) string {
	if component.ComponentKind == "" {
		return "components"
	}
	return defaultComponentDir(component.ComponentKind)
}

func passesFromComponent(component ComponentPlan) []string {
	for _, file := range component.Files {
		if len(file.Provenance.Passes) > 0 {
			return append([]string{}, file.Provenance.Passes...)
		}
	}
	return nil
}

func callbackName(action string) string {
	parts := strings.FieldsFunc(action, func(r rune) bool { return r == '_' || r == '-' || r == '.' })
	for i, part := range parts {
		if part == "" {
			continue
		}
		parts[i] = strings.ToUpper(part[:1]) + part[1:]
	}
	return "on" + strings.Join(parts, "")
}

func defaultVisualState(component ComponentPlan) string {
	if len(component.VisualStates) == 0 {
		return "default"
	}
	return component.VisualStates[0]
}

func tsStringArray(values []string) string {
	quoted := make([]string, 0, len(values))
	for _, value := range values {
		quoted = append(quoted, tsString(value))
	}
	return "[" + strings.Join(quoted, ", ") + "]"
}

func storyDescription(component ComponentPlan) string {
	parts := []string{
		fmt.Sprintf("Generated React scaffold for Web template %s.", component.TemplateID),
		"MetaDesignSystem: web.",
	}
	if len(component.RealizesRepresentations) > 0 {
		parts = append(parts, "Representations: "+strings.Join(component.RealizesRepresentations, ", ")+".")
	}
	if len(component.RealizesActions) > 0 {
		parts = append(parts, "Actions: "+strings.Join(component.RealizesActions, ", ")+".")
	}
	return strings.Join(parts, " ")
}

func tsString(value string) string {
	b, _ := json.Marshal(value)
	return string(b)
}

func cssGeneratedHeader(component ComponentPlan) string {
	return fmt.Sprintf(`/*
 * Code generated by dmeta scaffold-react. This is a generated template stylesheet.
 * Metadata: %s
 * To promote: copy it with the component template, remove .template from filenames, tune CSS in src/components, and update the registry/Storybook.
 * Do not edit this generated file directly; edit the IR/generator or promote first.
 */

`, metadataFileName(component))
}

func webTypeScriptPrelude(_ ScaffoldPlan, component ComponentPlan, file PlannedFile) string {
	metadataPath := relativeMetadataPath(component, file)
	return fmt.Sprintf(`// Code generated by dmeta scaffold-react. This is a generated template, not the promoted source.
// Metadata: %s
// To promote: copy/rename into hand-owned src/components/%s/%s, remove .template from filenames, wire adapters/Storybook, and update src/dmeta/widgetRegistry.ts.
// Do not edit this generated file directly; edit the IR/generator or promote first.

`, metadataPath, storybookKind(component), component.ComponentName)
}

func relativeMetadataPath(component ComponentPlan, file PlannedFile) string {
	metadataPath := filepath.Join(component.ComponentDir, metadataFileName(component))
	if file.Path == "" {
		return "./" + metadataFileName(component)
	}
	rel, err := filepath.Rel(filepath.Dir(file.Path), metadataPath)
	if err != nil {
		return "./" + metadataFileName(component)
	}
	rel = filepath.ToSlash(rel)
	if rel == metadataFileName(component) || !strings.HasPrefix(rel, ".") {
		rel = "./" + rel
	}
	return rel
}

func metadataFileName(component ComponentPlan) string {
	return component.ComponentName + ".metadata.json"
}

func webGeneratedMetadata(plan ScaffoldPlan, component ComponentPlan, file PlannedFile) genmeta.GeneratedFileMetadata {
	generated := plan.Generated
	if generated.By == "" {
		generated.By = "dmeta scaffold-react"
	}
	meta := genmeta.GeneratedFileMetadata{
		Generated: generated,
		Artifact: genmeta.ArtifactInfo{
			Path:       file.Path,
			Kind:       file.Kind,
			Language:   reactLanguageForPath(file.Path),
			Symbol:     file.Symbol,
			Promotable: webFileIsPromotable(file.Kind),
		},
		Pipeline: genmeta.PipelineInfo{
			SemanticRoot:     plan.SemanticRoot,
			InteractionsRoot: plan.InteractionsRoot,
			MetaDesignSystem: "web",
			Target:           plan.TargetID,
			Passes:           passesFromComponent(component),
		},
		Sources: []genmeta.SourceReference{
			{Path: plan.SemanticRoot, Role: "semantic package", Why: "Provides domain types, archetypes, capabilities, and examples used by Web lowering."},
			{Path: plan.InteractionsRoot, Role: "interaction package", Why: "Provides action and representation obligations lowered into Web widget obligations."},
			{Path: plan.WebRoot, Role: "Web MetaDesignSystem", Why: "Provides widget templates, Web lowering rules, and target-independent web obligations."},
			{Path: plan.TargetFile, Role: "React target", Why: "Provides React target defaults and file kinds for this scaffold."},
		},
		Semantics: &genmeta.SemanticGuidance{
			DomainTypes:     append([]string{}, component.SourceDomainTypes...),
			Representations: append([]string{}, component.RealizesRepresentations...),
			Actions:         append([]string{}, component.RealizesActions...),
			SourceRules:     append([]string{}, component.SourceRules...),
		},
		Web: &genmeta.WebGuidance{
			TemplateID:    component.TemplateID,
			Variant:       component.Variant,
			Slots:         append([]string{}, component.Slots...),
			VisualStates:  append([]string{}, component.VisualStates...),
			EventBindings: append([]string{}, component.EventBindings...),
			ComponentSystem: &genmeta.ComponentSystemGuidance{
				Kind:        component.ComponentKind,
				Specificity: component.ComponentSpecificity,
				Family:      component.ComponentFamily,
				Role:        component.ComponentRole,
				Lifecycle:   component.ComponentLifecycle,
			},
			Composition: &genmeta.ComponentCompositionInfo{
				Uses:     componentDependencyIDs(component),
				Provides: append([]string{}, component.Template.Composition.Provides...),
			},
		},
		React: &genmeta.ReactGuidance{
			PackageName:   component.PackageName,
			Files:         generatedReactFileRefs(component.Files),
			ComponentPath: component.ComponentDir,
			Props:         reactPropContractRefs(component),
			Events:        reactEventContractRefs(component),
		},
		Guidance: &genmeta.HumanGuidance{
			Summary: "Generated Web React scaffold. Promote intentionally before hand editing and keep the JSON metadata sidecar visible to maintain Semantic IR and Web MetaDesignSystem context.",
			ImplementationNotes: []string{
				"Use the sibling metadata JSON sidecar to trace props, slots, visual states, and event bindings back to Web lowering obligations.",
				"When promoted, copy or rename *.template.* files into hand-owned source, remove the .template suffix, update Storybook, and update src/dmeta/widgetRegistry.ts.",
			},
		},
	}
	return genmeta.WithDefaults(meta)
}

func generatedReactFileRefs(files []PlannedFile) []genmeta.FileRef {
	refs := make([]genmeta.FileRef, 0, len(files))
	for _, file := range files {
		refs = append(refs, genmeta.FileRef{Kind: file.Kind, Path: file.Path, Symbol: file.Symbol})
	}
	return refs
}

func componentDependencyIDs(component ComponentPlan) []string {
	ids := make([]string, 0, len(component.Template.Composition.Uses))
	for _, dep := range component.Template.Composition.Uses {
		if dep.Template != "" {
			ids = append(ids, dep.Template)
			continue
		}
		if dep.Component != "" {
			ids = append(ids, dep.Component)
		}
	}
	return ids
}

func reactPropContractRefs(component ComponentPlan) []genmeta.ReactPropContractRef {
	refs := []genmeta.ReactPropContractRef{}
	for _, propName := range sortedPropNames(component.Template.Contract.Props) {
		contract := component.Template.Contract.Props[propName]
		if strings.HasSuffix(propName, "Props") {
			for _, fieldName := range sortedFieldNames(contract.Fields) {
				field := contract.Fields[fieldName]
				refs = append(refs, genmeta.ReactPropContractRef{Name: fieldName, Type: contractTypeLabel(field), Source: firstNonEmpty(field.Source, contract.Source), SourceRef: firstNonEmpty(field.SourceRef, contract.SourceRef), Required: field.Required, Values: append([]string{}, field.Values...), Description: field.Description})
			}
			continue
		}
		refs = append(refs, genmeta.ReactPropContractRef{Name: propName, Type: "object", Source: contract.Source, SourceRef: contract.SourceRef, Required: contract.Required, Description: contract.Description})
	}
	return refs
}

func reactEventContractRefs(component ComponentPlan) []genmeta.ReactEventContractRef {
	refs := []genmeta.ReactEventContractRef{}
	for _, name := range sortedEventNames(component.Template.Contract.Events) {
		event := component.Template.Contract.Events[name]
		refs = append(refs, genmeta.ReactEventContractRef{Name: name, ActionRef: event.ActionRef, PayloadType: event.PayloadType, Source: event.Source, Required: event.Required, Description: event.Description})
	}
	for name, slot := range component.Template.Contract.ActionSlots {
		refs = append(refs, genmeta.ReactEventContractRef{Name: name, ActionRef: slot.ActionRef, PayloadType: firstNonEmpty(slot.PayloadType, slot.Accepts), Source: slot.Source, Description: slot.Description})
	}
	return refs
}

func contractTypeLabel(field validator.PropField) string {
	return firstNonEmpty(field.Type, field.TypeRef, field.ItemTypeRef)
}

func webFileIsPromotable(kind string) bool {
	switch kind {
	case "component", "types", "stories", "style", "adapter_todo", "readme", "barrel":
		return true
	default:
		return false
	}
}

func reactLanguageForPath(path string) string {
	switch filepath.Ext(path) {
	case ".tsx":
		return "tsx"
	case ".ts":
		return "ts"
	case ".json":
		return "json"
	case ".css":
		return "css"
	case ".md":
		return "markdown"
	default:
		return "text"
	}
}
