import type { CommandBinding } from '../../generic/clim/types';
import type { DeliActionId, DeliCommandId } from './types';

export const deliCommandBindings: Record<DeliCommandId, CommandBinding<DeliCommandId, DeliActionId>> = {
  CUSTOMIZE: {
    id: 'CUSTOMIZE',
    actionId: 'select_menu_item',
    label: 'CUSTOMIZE',
    summary: 'Enter the item customization/detail view for a selected menu item.',
    views: ['menu'],
    presentationType: 'pbui.action_presentation',
    surface: 'context_menu',
    handler: 'deli.selectMenuItem',
    inputMapping: { item_ref: 'selected_presentation' },
    requiresConfirmation: false,
  },
  'FILTER-DIETARY': {
    id: 'FILTER-DIETARY',
    actionId: 'filter_by_dietary',
    label: 'FILTER-DIETARY',
    summary: 'Filter menu or substitution choices by a dietary/allergen tag.',
    views: ['menu'],
    presentationType: 'pbui.action_presentation',
    surface: 'command_line',
    handler: 'deli.filterByDietary',
    inputMapping: { dietary_tag: 'command_argument:tag' },
    requiresConfirmation: false,
  },
  'FILTER-BY-CATEGORY': {
    id: 'FILTER-BY-CATEGORY',
    actionId: 'filter_by_category',
    label: 'FILTER-BY-CATEGORY',
    summary: 'Filter menu choices by category.',
    views: ['menu'],
    presentationType: 'pbui.action_presentation',
    surface: 'command_line',
    handler: 'deli.filterByCategory',
    inputMapping: { category: 'command_argument:category' },
    requiresConfirmation: false,
  },
  'REMOVE-INGREDIENT': {
    id: 'REMOVE-INGREDIENT',
    actionId: 'remove_part',
    label: 'REMOVE-INGREDIENT',
    summary: 'Remove one ingredient from the current composition draft.',
    views: ['detail'],
    presentationType: 'pbui.action_presentation',
    surface: 'context_menu',
    handler: 'deli.removeIngredient',
    inputMapping: { composition_ref: 'current_draft', part_ref: 'selected_presentation' },
    requiresConfirmation: false,
  },
  'ADD-TO-ORDER': {
    id: 'ADD-TO-ORDER',
    actionId: 'add_to_order',
    label: 'ADD-TO-ORDER',
    summary: 'Add the current configured item draft to the order/cart.',
    views: ['detail'],
    presentationType: 'pbui.action_presentation',
    surface: 'context_menu',
    handler: 'deli.addToOrder',
    inputMapping: { draft_ref: 'current_draft' },
    requiresConfirmation: false,
  },
  APPLY: {
    id: 'APPLY',
    actionId: 'apply_substitution',
    label: 'APPLY',
    summary: 'Apply the selected substitution candidate to the current draft.',
    views: ['substitution'],
    presentationType: 'pbui.action_presentation',
    surface: 'context_menu',
    handler: 'deli.applySubstitution',
    inputMapping: {
      composition_ref: 'current_draft',
      original_part_ref: 'selected_removed_part',
      replacement_candidate_ref: 'selected_presentation',
    },
    requiresConfirmation: false,
  },
  DESCRIBE: {
    id: 'DESCRIBE',
    actionId: 'describe_subject',
    label: 'DESCRIBE',
    summary: 'Inspect or describe the selected presentation.',
    views: ['substitution'],
    presentationType: 'pbui.action_presentation',
    surface: 'help_surface',
    handler: 'deli.describeSubject',
    inputMapping: { subject_ref: 'selected_presentation' },
    requiresConfirmation: false,
  },
  CART: {
    id: 'CART',
    actionId: 'navigate_to_cart',
    label: 'CART',
    summary: 'Navigate to the cart/review view.',
    views: ['menu', 'detail'],
    presentationType: 'pbui.action_presentation',
    surface: 'command_line',
    handler: 'deli.navigateToCart',
    inputMapping: {},
    requiresConfirmation: false,
  },
  BACK: {
    id: 'BACK',
    actionId: 'return_to_menu',
    label: 'BACK',
    summary: 'Return from detail or substitution flow to the previous/menu surface.',
    views: ['detail', 'substitution'],
    presentationType: 'pbui.action_presentation',
    surface: 'command_line',
    handler: 'deli.returnToMenu',
    inputMapping: {},
    requiresConfirmation: false,
  },
  MENU: {
    id: 'MENU',
    actionId: 'return_to_menu',
    label: 'MENU',
    summary: 'Return to the menu browsing surface.',
    views: ['cart', 'help', 'tracker'],
    presentationType: 'pbui.action_presentation',
    surface: 'command_line',
    handler: 'deli.returnToMenu',
    inputMapping: {},
    requiresConfirmation: false,
  },
  HELP: {
    id: 'HELP',
    actionId: 'show_help',
    label: 'HELP',
    summary: 'Open the help/documentation surface.',
    views: ['menu', 'detail', 'cart', 'tracker'],
    presentationType: 'pbui.action_presentation',
    surface: 'command_line',
    handler: 'deli.showHelp',
    inputMapping: {},
    requiresConfirmation: false,
  },
  'PLACE-ORDER': {
    id: 'PLACE-ORDER',
    actionId: 'submit_order',
    label: 'PLACE-ORDER',
    summary: 'Submit the cart as an order after confirmation.',
    views: ['cart'],
    presentationType: 'pbui.action_presentation',
    surface: 'confirm_prompt',
    handler: 'deli.submitOrder',
    inputMapping: { cart_ref: 'current_cart' },
    requiresConfirmation: true,
    confirmation: {
      surface: 'confirm_prompt',
      prompt: 'Submit the current cart as an order?',
      confirmLabel: 'CONFIRM PLACE-ORDER',
      cancelLabel: 'CANCEL',
    },
  },
};

export function commandBindingsForView(viewId: string) {
  return Object.values(deliCommandBindings).filter((binding) => binding.views.includes(viewId));
}
