// Code generated by logcopter-gen; DO NOT EDIT.

package metadata

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("go-go-golems.dmeta.pkg.dmeta.generator.metadata")
