package metadata

// GeneratedFileMetadata is the common provenance envelope emitted by DMETA
// renderers. The structure is JSON-compatible so it can be rendered as JSON
// sidecars or as TypeScript `as const` exports for development tooling.
type GeneratedFileMetadata struct {
	SchemaVersion int               `json:"schemaVersion"`
	Generated     GeneratedInfo     `json:"generated"`
	Artifact      ArtifactInfo      `json:"artifact"`
	Pipeline      PipelineInfo      `json:"pipeline"`
	Sources       []SourceReference `json:"sources,omitempty"`
	Semantics     *SemanticGuidance `json:"semantics,omitempty"`
	Web           *WebGuidance      `json:"web,omitempty"`
	PBUI          *PBUIGuidance     `json:"pbui,omitempty"`
	React         *ReactGuidance    `json:"react,omitempty"`
	Guidance      *HumanGuidance    `json:"guidance,omitempty"`
	Promotion     *PromotionInfo    `json:"promotion,omitempty"`
}

type GeneratedInfo struct {
	At               string `json:"at"`
	By               string `json:"by"`
	Command          string `json:"command"`
	WorkingDirectory string `json:"workingDirectory,omitempty"`
	GitCommit        string `json:"gitCommit,omitempty"`
}

type ArtifactInfo struct {
	Path       string `json:"path"`
	Kind       string `json:"kind"`
	Language   string `json:"language,omitempty"`
	Symbol     string `json:"symbol,omitempty"`
	Promotable bool   `json:"promotable"`
}

type PipelineInfo struct {
	SemanticRoot     string   `json:"semanticRoot,omitempty"`
	InteractionsRoot string   `json:"interactionsRoot,omitempty"`
	MetaDesignSystem string   `json:"metaDesignSystem,omitempty"`
	ProfileRoot      string   `json:"profileRoot,omitempty"`
	Target           string   `json:"target,omitempty"`
	Passes           []string `json:"passes,omitempty"`
}

type SourceReference struct {
	Path         string `json:"path"`
	Role         string `json:"role"`
	Why          string `json:"why"`
	ArtifactType string `json:"artifactType,omitempty"`
}

type SemanticGuidance struct {
	DomainTypes     []string `json:"domainTypes,omitempty"`
	Archetypes      []string `json:"archetypes,omitempty"`
	Capabilities    []string `json:"capabilities,omitempty"`
	Representations []string `json:"representations,omitempty"`
	Actions         []string `json:"actions,omitempty"`
	SourceRules     []string `json:"sourceRules,omitempty"`
}

type WebGuidance struct {
	TemplateID    string   `json:"templateId,omitempty"`
	Variant       string   `json:"variant,omitempty"`
	Slots         []string `json:"slots,omitempty"`
	VisualStates  []string `json:"visualStates,omitempty"`
	EventBindings []string `json:"eventBindings,omitempty"`
}

type PBUIGuidance struct {
	PresentationType string   `json:"presentationType,omitempty"`
	PresenterIntent  string   `json:"presenterIntent,omitempty"`
	RecognizerIntent string   `json:"recognizerIntent,omitempty"`
	ViewID           string   `json:"viewId,omitempty"`
	SurfaceID        string   `json:"surfaceId,omitempty"`
	BindingComponent string   `json:"bindingComponent,omitempty"`
	StyleClasses     []string `json:"styleClasses,omitempty"`
}

type ReactGuidance struct {
	PackageName string    `json:"packageName,omitempty"`
	Files       []FileRef `json:"files,omitempty"`
}

type FileRef struct {
	Kind   string `json:"kind"`
	Path   string `json:"path"`
	Symbol string `json:"symbol,omitempty"`
}

type HumanGuidance struct {
	Summary             string   `json:"summary,omitempty"`
	ImplementationNotes []string `json:"implementationNotes,omitempty"`
}

type PromotionInfo struct {
	Promotable   bool     `json:"promotable"`
	Status       string   `json:"status,omitempty"`
	Instructions []string `json:"instructions,omitempty"`
	Changelog    []string `json:"changelog,omitempty"`
}

func DefaultPromotionInfo(promotable bool, generatedAt string, generatedBy string) *PromotionInfo {
	if !promotable {
		return &PromotionInfo{
			Promotable:   false,
			Status:       "regenerate",
			Instructions: []string{"Do not edit this file by hand; regenerate it from DMETA sources."},
		}
	}
	entry := "Generated by " + generatedBy + ". Initial scaffold."
	if generatedAt != "" {
		entry = generatedAt + ": " + entry
	}
	return &PromotionInfo{
		Promotable: true,
		Status:     "scaffold",
		Instructions: []string{
			"Keep dmetaGeneratedMetadata unless this file is deliberately detached from DMETA.",
			"Record semantic, behavioral, prop, or visual changes in the promotion changelog.",
			"Update Storybook coverage when visual states or interaction behavior change.",
		},
		Changelog: []string{entry},
	}
}
