package metadata

import (
	"encoding/json"
	"strings"
	"testing"
)

func TestRenderTypeScriptPreludeIncludesHeaderMetadataAndPromotion(t *testing.T) {
	meta := WithDefaults(GeneratedFileMetadata{
		Generated: GeneratedInfo{At: "2026-05-25T12:00:00Z", By: "dmeta scaffold-react", Command: "dmeta scaffold-react --dry-run=false"},
		Artifact:  ArtifactInfo{Path: "src/AppointmentBlock.tsx", Kind: "component", Language: "tsx", Symbol: "AppointmentBlock", Promotable: true},
		Pipeline:  PipelineInfo{SemanticRoot: "examples/appointment", MetaDesignSystem: "web", Target: "react", Passes: []string{"validate-ir", "lower-web", "scaffold-react"}},
		Sources:   []SourceReference{{Path: "examples/appointment/core-model.yaml", Role: "domain mappings", Why: "Defines Appointment."}},
	})
	out, err := RenderTypeScriptPrelude(meta)
	if err != nil {
		t.Fatalf("render prelude: %v", err)
	}
	for _, want := range []string{
		"// Code generated by dmeta scaffold-react. DO NOT EDIT until promoted.",
		"// Generated at: 2026-05-25T12:00:00Z",
		"// Command: dmeta scaffold-react --dry-run=false",
		"export const dmetaGeneratedMetadata = {",
		"\"path\": \"examples/appointment/core-model.yaml\"",
		"DMETA promotion status: scaffold",
		"Promotion changelog:",
	} {
		if !strings.Contains(out, want) {
			t.Fatalf("expected output to contain %q\n%s", want, out)
		}
	}
}

func TestRenderJSONIsParseable(t *testing.T) {
	meta := WithDefaults(GeneratedFileMetadata{
		Generated: GeneratedInfo{By: "dmeta scaffold-pbui-react"},
		Artifact:  ArtifactInfo{Path: "registries/actions.ts", Kind: "registry", Promotable: false},
	})
	payload, err := RenderJSON(meta)
	if err != nil {
		t.Fatalf("render json: %v", err)
	}
	var decoded GeneratedFileMetadata
	if err := json.Unmarshal(payload, &decoded); err != nil {
		t.Fatalf("unmarshal: %v\n%s", err, string(payload))
	}
	if decoded.SchemaVersion != 1 {
		t.Fatalf("expected schema version 1, got %d", decoded.SchemaVersion)
	}
	if decoded.Promotion == nil || decoded.Promotion.Promotable {
		t.Fatalf("expected regenerate-only promotion info: %#v", decoded.Promotion)
	}
}
