package metadata

import (
	"bytes"
	"encoding/json"
	"fmt"
	"strings"
)

func RenderHeader(meta GeneratedFileMetadata) string {
	var b strings.Builder
	by := meta.Generated.By
	if by == "" {
		by = "dmeta"
	}
	b.WriteString("// Code generated by ")
	b.WriteString(by)
	b.WriteString(". DO NOT EDIT until promoted.\n")
	if meta.Generated.At != "" {
		b.WriteString("// Generated at: ")
		b.WriteString(meta.Generated.At)
		b.WriteString("\n")
	}
	if meta.Generated.Command != "" {
		b.WriteString("// Command: ")
		b.WriteString(meta.Generated.Command)
		b.WriteString("\n")
	}
	b.WriteString("// Metadata: dmetaGeneratedMetadata is parseable provenance for tooling and LLM-assisted development.\n\n")
	return b.String()
}

func RenderTypeScriptConst(name string, value any) (string, error) {
	if name == "" {
		name = "dmetaGeneratedMetadata"
	}
	payload, err := json.MarshalIndent(value, "", "  ")
	if err != nil {
		return "", err
	}
	var b bytes.Buffer
	b.WriteString("export const ")
	b.WriteString(name)
	b.WriteString(" = ")
	b.Write(payload)
	b.WriteString(" as const;\n\n")
	return b.String(), nil
}

func RenderTypeScriptPrelude(meta GeneratedFileMetadata) (string, error) {
	metadataConst, err := RenderTypeScriptConst("dmetaGeneratedMetadata", meta)
	if err != nil {
		return "", err
	}
	return RenderHeader(meta) + metadataConst + RenderPromotionComment(meta), nil
}

func RenderPromotionComment(meta GeneratedFileMetadata) string {
	if meta.Promotion == nil {
		return ""
	}
	var b strings.Builder
	b.WriteString("/**\n")
	if meta.Promotion.Promotable {
		status := meta.Promotion.Status
		if status == "" {
			status = "scaffold"
		}
		b.WriteString(" * DMETA promotion status: ")
		b.WriteString(status)
		b.WriteString("\n")
		b.WriteString(" *\n")
		b.WriteString(" * Promotion instructions:\n")
		for _, instruction := range meta.Promotion.Instructions {
			b.WriteString(" * - ")
			b.WriteString(instruction)
			b.WriteString("\n")
		}
		b.WriteString(" *\n")
		b.WriteString(" * Promotion changelog:\n")
		for _, entry := range meta.Promotion.Changelog {
			b.WriteString(" * - ")
			b.WriteString(entry)
			b.WriteString("\n")
		}
	} else {
		b.WriteString(" * DMETA generated artifact: regenerate-only\n")
		b.WriteString(" *\n")
		b.WriteString(" * Instructions:\n")
		for _, instruction := range meta.Promotion.Instructions {
			b.WriteString("\n * - ")
			b.WriteString(instruction)
		}
		b.WriteString("\n")
	}
	b.WriteString(" */\n\n")
	return b.String()
}

func RenderJSON(meta GeneratedFileMetadata) ([]byte, error) {
	if meta.SchemaVersion == 0 {
		meta.SchemaVersion = 1
	}
	payload, err := json.MarshalIndent(meta, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("marshal generated metadata: %w", err)
	}
	return append(payload, '\n'), nil
}

func WithDefaults(meta GeneratedFileMetadata) GeneratedFileMetadata {
	if meta.SchemaVersion == 0 {
		meta.SchemaVersion = 1
	}
	if meta.Promotion == nil {
		meta.Promotion = DefaultPromotionInfo(meta.Artifact.Promotable, meta.Generated.At, meta.Generated.By)
	}
	return meta
}
