package widgets

import (
	"bytes"
	"encoding/json"
	"fmt"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/go-go-golems/dmeta/pkg/dmeta/validator"
)

const generatedHeader = "// Code generated by dmeta scaffold-instance from a DMETA instance manifest. DO NOT EDIT until promoted.\n\n"

func Generate(instance InstanceManifest, resolved []ResolvedTemplate, outDir string) ([]GeneratedFile, error) {
	if outDir == "" {
		outDir = instance.Generation.OutputDir
	}
	if outDir == "" {
		return nil, fmt.Errorf("no output directory supplied and instance generation.output_dir is empty")
	}

	var files []GeneratedFile
	var index bytes.Buffer
	index.WriteString(generatedHeader)
	index.WriteString(fmt.Sprintf("// Instance: %s (%s)\n\n", instance.ID, instance.Name))

	for _, rt := range resolved {
		name := componentName(rt)
		base := filepath.Join(outDir, name)
		files = append(files,
			GeneratedFile{Path: filepath.Join(base, name+".types.ts"), Content: []byte(renderTypes(name, rt))},
			GeneratedFile{Path: filepath.Join(base, name+".tsx"), Content: []byte(renderComponent(name, rt))},
			GeneratedFile{Path: filepath.Join(base, name+".metadata.ts"), Content: []byte(renderMetadata(name, instance, rt))},
			GeneratedFile{Path: filepath.Join(base, name+".stories.tsx"), Content: []byte(renderStories(name, instance, rt))},
			GeneratedFile{Path: filepath.Join(base, "index.ts"), Content: []byte(renderBarrel(name))},
		)
		index.WriteString(fmt.Sprintf("export * from \"./%s\";\n", name))
	}
	files = append(files, GeneratedFile{Path: filepath.Join(outDir, "index.ts"), Content: index.Bytes()})
	files = append(files, GeneratedFile{Path: filepath.Join(outDir, "README.md"), Content: []byte(renderReadme(instance, resolved))})
	return files, nil
}

func componentName(rt ResolvedTemplate) string {
	if rt.Selected.As != "" {
		return rt.Selected.As
	}
	return rt.Template.Name
}

func renderTypes(name string, rt ResolvedTemplate) string {
	var b bytes.Buffer
	b.WriteString(generatedHeader)
	aliases := collectAliases(rt)
	for _, alias := range aliases {
		b.WriteString(fmt.Sprintf("export type %s = unknown;\n", alias))
	}
	if len(aliases) > 0 {
		b.WriteString("\n")
	}
	b.WriteString(fmt.Sprintf("export type %sProps = {\n", name))
	fields := fieldsForWidget(rt.Template)
	for _, fieldName := range sortedKeys(fields) {
		field := fields[fieldName]
		optional := ""
		if !field.Required {
			optional = "?"
		}
		b.WriteString(fmt.Sprintf("  %s%s: %s;\n", tsField(fieldName), optional, tsType(field.Type)))
	}
	for slotName, slot := range rt.Template.Contract.ActionSlots {
		b.WriteString(fmt.Sprintf("  %s?: (payload: %s) => void;\n", tsField(slotName), tsType(slot.Accepts)))
	}
	b.WriteString("};\n")
	return b.String()
}

func renderComponent(name string, rt ResolvedTemplate) string {
	return fmt.Sprintf(`%simport type { %sProps } from "./%s.types";

export function %s(props: %sProps) {
  return (
    <section data-dmeta-widget=%q data-dmeta-template=%q data-dmeta-variant=%q>
      <header>
        <strong>%s</strong>
        <span> generated from %s</span>
      </header>
      <pre>{JSON.stringify(props, null, 2)}</pre>
    </section>
  );
}

export default %s;
`, generatedHeader, name, name, name, name, rt.Template.ID, rt.Template.ID, rt.Selected.Variant, name, rt.Template.ID, name)
}

func renderMetadata(name string, instance InstanceManifest, rt ResolvedTemplate) string {
	payload := map[string]any{
		"generatedBy": "dmeta scaffold-instance",
		"instanceId":  instance.ID,
		"templateId":  rt.Template.ID,
		"selectedAs":  name,
		"variant":     rt.Selected.Variant,
		"reason":      rt.Selected.Reason,
		"category":    rt.Template.Template.Category,
		"adaptations": rt.Selected.Adaptations,
	}
	jsonPayload, _ := json.MarshalIndent(payload, "", "  ")
	return fmt.Sprintf("%sexport const %sMetadata = %s as const;\n", generatedHeader, name, string(jsonPayload))
}

func renderStories(name string, instance InstanceManifest, rt ResolvedTemplate) string {
	storyName := "Default"
	if len(rt.Template.Stories) > 0 {
		storyName = exportName(rt.Template.Stories[0])
	}
	return fmt.Sprintf(`%simport { %s } from "./%s";

export default {
  title: %q,
  component: %s,
};

export const %s = {
  args: {},
};
`, generatedHeader, name, name, instance.Name+"/"+name, name, storyName)
}

func renderBarrel(name string) string {
	return fmt.Sprintf("%sexport * from \"./%s\";\nexport * from \"./%s.types\";\nexport * from \"./%s.metadata\";\n", generatedHeader, name, name, name)
}

func renderReadme(instance InstanceManifest, resolved []ResolvedTemplate) string {
	var b bytes.Buffer
	b.WriteString(fmt.Sprintf("# Generated DMETA widgets for %s\n\n", instance.Name))
	b.WriteString(instance.Summary + "\n\n")
	b.WriteString("## Selected templates\n\n")
	for _, rt := range resolved {
		b.WriteString(fmt.Sprintf("- `%s` from `%s`", componentName(rt), rt.Template.ID))
		if rt.Selected.Variant != "" {
			b.WriteString(fmt.Sprintf(" variant `%s`", rt.Selected.Variant))
		}
		if rt.Selected.Reason != "" {
			b.WriteString(fmt.Sprintf(": %s", rt.Selected.Reason))
		}
		b.WriteString("\n")
	}
	if len(instance.ExcludedTemplates) > 0 {
		b.WriteString("\n## Explicitly excluded templates\n\n")
		for _, ex := range instance.ExcludedTemplates {
			b.WriteString(fmt.Sprintf("- `%s`: %s\n", ex.Template, ex.Reason))
		}
	}
	b.WriteString("\nThese files are scaffolds. Promote and edit concrete widgets intentionally; do not blindly regenerate over promoted work.\n")
	return b.String()
}

func fieldsForWidget(widget validator.Widget) map[string]validator.PropField {
	for _, iface := range widget.Contract.Props {
		if len(iface.Fields) > 0 {
			return iface.Fields
		}
	}
	return map[string]validator.PropField{"subject": {Type: "unknown", Required: true}}
}

func collectAliases(rt ResolvedTemplate) []string {
	aliases := map[string]bool{
		"PresentationRef":           true,
		"PresentationActionRequest": true,
	}
	add := func(t string) {
		for _, token := range identifiers(t) {
			if isPrimitiveType(token) || isReservedWord(token) {
				continue
			}
			aliases[token] = true
		}
	}
	for _, field := range fieldsForWidget(rt.Template) {
		add(field.Type)
	}
	for _, slot := range rt.Template.Contract.ActionSlots {
		add(slot.Accepts)
	}
	out := sortedKeys(aliases)
	return out
}

var identRe = regexp.MustCompile(`[A-Za-z_][A-Za-z0-9_]*`)

func identifiers(s string) []string { return identRe.FindAllString(s, -1) }

func isPrimitiveType(s string) bool {
	switch s {
	case "string", "number", "boolean", "unknown", "void", "integer", "true", "false":
		return true
	default:
		return false
	}
}

func isReservedWord(s string) bool {
	switch s {
	case "type", "const", "let", "var", "export", "import", "from", "null", "undefined":
		return true
	default:
		return false
	}
}

func tsType(t string) string {
	if t == "" {
		return "unknown"
	}
	if t == "integer" {
		return "number"
	}
	return t
}

func tsField(s string) string {
	if identRe.FindString(s) == s {
		return s
	}
	return fmt.Sprintf("%q", s)
}

func exportName(s string) string {
	parts := regexp.MustCompile(`[^A-Za-z0-9]+`).Split(s, -1)
	var out string
	for _, p := range parts {
		if p == "" {
			continue
		}
		out += strings.ToUpper(p[:1]) + p[1:]
	}
	if out == "" {
		return "Default"
	}
	return out
}

func sortedKeys[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
