package widgets

import (
	"bytes"
	"encoding/json"
	"fmt"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/go-go-golems/dmeta/pkg/dmeta/validator"
)

const generatedHeader = "// Code generated by dmeta scaffold-instance from a DMETA instance manifest. DO NOT EDIT until promoted.\n\n"

func Generate(instance InstanceManifest, resolved []ResolvedTemplate, outDir string) ([]GeneratedFile, error) {
	if outDir == "" {
		outDir = instance.Generation.OutputDir
	}
	if outDir == "" {
		return nil, fmt.Errorf("no output directory supplied and instance generation.output_dir is empty")
	}

	var files []GeneratedFile
	var index bytes.Buffer
	index.WriteString(generatedHeader)
	index.WriteString(fmt.Sprintf("// Instance: %s (%s)\n\n", instance.ID, instance.Name))

	for _, rt := range resolved {
		name := componentName(rt)
		base := filepath.Join(outDir, name)
		files = append(files,
			GeneratedFile{Path: filepath.Join(base, name+".types.ts"), Content: []byte(renderTypes(name, rt))},
			GeneratedFile{Path: filepath.Join(base, name+".tsx"), Content: []byte(renderComponent(name, rt))},
			GeneratedFile{Path: filepath.Join(base, name+".metadata.ts"), Content: []byte(renderMetadata(name, instance, rt))},
			GeneratedFile{Path: filepath.Join(base, name+".stories.tsx"), Content: []byte(renderStories(name, instance, rt))},
			GeneratedFile{Path: filepath.Join(base, "index.ts"), Content: []byte(renderBarrel(name))},
		)
		if rt.Template.Generation.ShouldEmitAdapterTODOs() {
			files = append(files, GeneratedFile{Path: filepath.Join(base, name+".adapter.todo.ts"), Content: []byte(renderAdapterTODO(name, rt))})
		}
		index.WriteString(fmt.Sprintf("export * from \"./%s\";\n", name))
	}
	files = append(files, GeneratedFile{Path: filepath.Join(outDir, "index.ts"), Content: index.Bytes()})
	files = append(files, GeneratedFile{Path: filepath.Join(outDir, "README.md"), Content: []byte(renderReadme(instance, resolved))})
	return files, nil
}

func componentName(rt ResolvedTemplate) string {
	if rt.Selected.As != "" {
		return rt.Selected.As
	}
	return rt.Template.Name
}

func renderTypes(name string, rt ResolvedTemplate) string {
	var b bytes.Buffer
	b.WriteString(generatedHeader)
	aliases := collectAliases(rt)
	for _, alias := range aliases {
		b.WriteString(fmt.Sprintf("export type %s = unknown;\n", alias))
	}
	if len(aliases) > 0 {
		b.WriteString("\n")
	}
	b.WriteString(fmt.Sprintf("export type %sProps = {\n", name))
	fields := fieldsForWidget(rt.Template)
	for _, fieldName := range sortedKeys(fields) {
		field := fields[fieldName]
		optional := ""
		if !field.Required {
			optional = "?"
		}
		b.WriteString(fmt.Sprintf("  %s%s: %s;\n", tsField(fieldName), optional, tsType(field.Type)))
	}
	for slotName, slot := range rt.Template.Contract.ActionSlots {
		b.WriteString(fmt.Sprintf("  %s?: (payload: %s) => void;\n", tsField(slotName), tsType(slot.Accepts)))
	}
	b.WriteString("};\n")
	return b.String()
}

func renderComponent(name string, rt ResolvedTemplate) string {
	docComment := ""
	if rt.Template.Generation.ShouldEmitDocComments() {
		docComment = renderSemanticDocComment(name, rt) + "\n"
	}
	return fmt.Sprintf(`%simport type { %sProps } from "./%s.types";

%sexport function %s(props: %sProps) {
  return (
    <section data-dmeta-widget=%q data-dmeta-template=%q data-dmeta-variant=%q>
      <header>
        <strong>%s</strong>
        <span> generated from %s</span>
      </header>
      <pre>{JSON.stringify(props, null, 2)}</pre>
    </section>
  );
}

export default %s;
`, generatedHeader, name, name, docComment, name, name, rt.Template.ID, rt.Template.ID, rt.Selected.Variant, name, rt.Template.ID, name)
}

func renderSemanticDocComment(name string, rt ResolvedTemplate) string {
	var b strings.Builder
	b.WriteString("/**\n")
	b.WriteString(fmt.Sprintf(" * %s\n", name))
	b.WriteString(" *\n")
	b.WriteString(fmt.Sprintf(" * Reflection-first scaffold generated from `%s`.\n", rt.Template.ID))
	if rt.Selected.Reason != "" {
		b.WriteString(fmt.Sprintf(" * Selected because: %s\n", rt.Selected.Reason))
	}
	ctx := rt.Template.SemanticContext
	if hasSemanticContext(ctx) {
		b.WriteString(" *\n")
		b.WriteString(" * Semantic context:\n")
		for _, arch := range ctx.Archetypes {
			b.WriteString(fmt.Sprintf(" * - Archetype: %s\n", arch))
		}
		for _, cap := range ctx.Capabilities {
			b.WriteString(fmt.Sprintf(" * - Capability: %s\n", cap))
		}
		for _, pres := range ctx.Presentations {
			b.WriteString(fmt.Sprintf(" * - Presentation: %s\n", pres))
		}
		if ctx.Intent != "" {
			b.WriteString(" *\n")
			b.WriteString(" * Intent:\n")
			writeWrappedDocLines(&b, ctx.Intent)
		}
		if ctx.InheritedContextNote != "" {
			b.WriteString(" *\n")
			b.WriteString(" * Inherited context note:\n")
			writeWrappedDocLines(&b, ctx.InheritedContextNote)
		}
	}
	if hasWidgetReflection(rt.Reflection) {
		b.WriteString(" *\n")
		b.WriteString(" * Resolved inherited context:\n")
		writeReflectionDocLines(&b, rt.Reflection)
	}
	if hasProjectionHints(rt.Template.ProjectionHints) {
		b.WriteString(" *\n")
		b.WriteString(" * Projection hints are scaffold guidance, not rigid layout requirements unless strict mode is enabled.\n")
		writeDocList(&b, "Required", rt.Template.ProjectionHints.Required)
		writeDocList(&b, "Recommended", rt.Template.ProjectionHints.Recommended)
		writeDocList(&b, "Optional", rt.Template.ProjectionHints.Optional)
		writeDocList(&b, "Documentation-only", rt.Template.ProjectionHints.DocumentationOnly)
	}
	b.WriteString(" */")
	return b.String()
}

func renderMetadata(name string, instance InstanceManifest, rt ResolvedTemplate) string {
	payload := map[string]any{
		"generatedBy": "dmeta scaffold-instance",
		"instanceId":  instance.ID,
		"templateId":  rt.Template.ID,
		"selectedAs":  name,
		"variant":     rt.Selected.Variant,
		"reason":      rt.Selected.Reason,
		"category":    rt.Template.Template.Category,
		"adaptations": rt.Selected.Adaptations,
		"generation": map[string]any{
			"scaffoldMode":            rt.Template.Generation.EffectiveScaffoldMode(),
			"emitSemanticMetadata":    rt.Template.Generation.ShouldEmitSemanticMetadata(),
			"emitDocComments":         rt.Template.Generation.ShouldEmitDocComments(),
			"emitAdapterTODOs":        rt.Template.Generation.ShouldEmitAdapterTODOs(),
			"strictProjectionAdapter": rt.Template.Generation.IsStrictProjectionAdapter(),
		},
	}
	if rt.Template.Generation.ShouldEmitSemanticMetadata() {
		if hasSemanticContext(rt.Template.SemanticContext) {
			payload["semanticContext"] = semanticContextPayload(rt.Template.SemanticContext)
		}
		if hasProjectionHints(rt.Template.ProjectionHints) {
			payload["projectionHints"] = projectionHintsPayload(rt.Template.ProjectionHints)
		}
		if hasWidgetReflection(rt.Reflection) {
			payload["resolvedSemanticContext"] = rt.Reflection
		}
	}
	jsonPayload, _ := json.MarshalIndent(payload, "", "  ")
	return fmt.Sprintf("%sexport const %sMetadata = %s as const;\n", generatedHeader, name, string(jsonPayload))
}

func renderStories(name string, instance InstanceManifest, rt ResolvedTemplate) string {
	storyName := "Default"
	if len(rt.Template.Stories) > 0 {
		storyName = exportName(rt.Template.Stories[0])
	}
	description := storyDescription(rt)
	return fmt.Sprintf(`%simport { %s } from "./%s";

export default {
  title: %q,
  component: %s,
  parameters: {
    docs: {
      description: {
        component: %s,
      },
    },
  },
};

export const %s = {
  args: {},
};
`, generatedHeader, name, name, instance.Name+"/"+name, name, tsString(description), storyName)
}

func storyDescription(rt ResolvedTemplate) string {
	parts := []string{fmt.Sprintf("Generated scaffold for `%s`.", rt.Template.ID)}
	if hasSemanticContext(rt.Template.SemanticContext) {
		ctx := rt.Template.SemanticContext
		semantic := []string{}
		semantic = append(semantic, ctx.Archetypes...)
		semantic = append(semantic, ctx.Capabilities...)
		semantic = append(semantic, ctx.Presentations...)
		if len(semantic) > 0 {
			parts = append(parts, "Semantic context: "+strings.Join(semantic, ", ")+".")
		}
	}
	if hasProjectionHints(rt.Template.ProjectionHints) {
		parts = append(parts, "Projection hints are scaffold guidance, not mandatory layout.")
	}
	return strings.Join(parts, " ")
}

func renderBarrel(name string) string {
	return fmt.Sprintf("%sexport * from \"./%s\";\nexport * from \"./%s.types\";\nexport * from \"./%s.metadata\";\n", generatedHeader, name, name, name)
}

func renderAdapterTODO(name string, rt ResolvedTemplate) string {
	var b strings.Builder
	b.WriteString(generatedHeader)
	b.WriteString("// This file is an implementation scaffold. Promote and edit intentionally.\n")
	b.WriteString("// It is not exported from the component barrel to avoid accidental runtime imports.\n\n")
	b.WriteString(fmt.Sprintf("import type { %sProps } from \"./%s.types\";\n\n", name, name))
	b.WriteString("/**\n")
	b.WriteString(fmt.Sprintf(" * TODO adapter for `%s`.\n", rt.Template.ID))
	if hasSemanticContext(rt.Template.SemanticContext) {
		b.WriteString(" *\n")
		b.WriteString(" * Semantic context:\n")
		writeDocList(&b, "Archetypes", rt.Template.SemanticContext.Archetypes)
		writeDocList(&b, "Capabilities", rt.Template.SemanticContext.Capabilities)
		writeDocList(&b, "Presentations", rt.Template.SemanticContext.Presentations)
	}
	if hasWidgetReflection(rt.Reflection) {
		b.WriteString(" *\n")
		b.WriteString(" * Resolved inherited context:\n")
		writeReflectionDocLines(&b, rt.Reflection)
	}
	if hasProjectionHints(rt.Template.ProjectionHints) {
		b.WriteString(" *\n")
		b.WriteString(" * Projection hints:\n")
		writeDocList(&b, "Required", rt.Template.ProjectionHints.Required)
		writeDocList(&b, "Recommended", rt.Template.ProjectionHints.Recommended)
		writeDocList(&b, "Optional", rt.Template.ProjectionHints.Optional)
		writeDocList(&b, "Documentation-only", rt.Template.ProjectionHints.DocumentationOnly)
	}
	b.WriteString(" */\n")
	b.WriteString(fmt.Sprintf("export function mapDomainTo%sProps(input: unknown): %sProps {\n", name, name))
	b.WriteString("  return {\n")
	for _, hint := range rt.Template.ProjectionHints.Required {
		b.WriteString(fmt.Sprintf("    // TODO: map required projection hint %s\n", hint))
	}
	for _, hint := range rt.Template.ProjectionHints.Recommended {
		b.WriteString(fmt.Sprintf("    // TODO: consider mapping recommended projection hint %s\n", hint))
	}
	for _, hint := range rt.Template.ProjectionHints.Optional {
		b.WriteString(fmt.Sprintf("    // TODO: optionally map projection hint %s when this variant needs it\n", hint))
	}
	for _, todo := range rt.Template.ProjectionHints.AdapterTODOs {
		b.WriteString(fmt.Sprintf("    // TODO: %s\n", todo))
	}
	b.WriteString("    subject: input,\n")
	b.WriteString("  } as unknown as " + name + "Props;\n")
	b.WriteString("}\n")
	return b.String()
}

func renderReadme(instance InstanceManifest, resolved []ResolvedTemplate) string {
	var b bytes.Buffer
	b.WriteString(fmt.Sprintf("# Generated DMETA widgets for %s\n\n", instance.Name))
	b.WriteString(instance.Summary + "\n\n")
	b.WriteString("## Selected templates\n\n")
	for _, rt := range resolved {
		b.WriteString(fmt.Sprintf("- `%s` from `%s`", componentName(rt), rt.Template.ID))
		if rt.Selected.Variant != "" {
			b.WriteString(fmt.Sprintf(" variant `%s`", rt.Selected.Variant))
		}
		if rt.Selected.Reason != "" {
			b.WriteString(fmt.Sprintf(": %s", rt.Selected.Reason))
		}
		b.WriteString("\n")
		if hasSemanticContext(rt.Template.SemanticContext) {
			b.WriteString(fmt.Sprintf("  - Semantic context: %s\n", semanticContextSummary(rt.Template.SemanticContext)))
		}
		if hasProjectionHints(rt.Template.ProjectionHints) {
			b.WriteString(fmt.Sprintf("  - Projection hints: %s\n", projectionHintSummary(rt.Template.ProjectionHints)))
		}
		if hasWidgetReflection(rt.Reflection) {
			b.WriteString(fmt.Sprintf("  - Resolved context: %s\n", reflectionSummary(rt.Reflection)))
		}
		if rt.Template.Generation.ShouldEmitAdapterTODOs() {
			b.WriteString(fmt.Sprintf("  - Adapter TODO scaffold: `%s.adapter.todo.ts`\n", componentName(rt)))
		}
	}
	if len(instance.ExcludedTemplates) > 0 {
		b.WriteString("\n## Explicitly excluded templates\n\n")
		for _, ex := range instance.ExcludedTemplates {
			b.WriteString(fmt.Sprintf("- `%s`: %s\n", ex.Template, ex.Reason))
		}
	}
	b.WriteString("\nThese files are scaffolds. Promote and edit concrete widgets intentionally; do not blindly regenerate over promoted work.\n")
	return b.String()
}

func fieldsForWidget(widget validator.Widget) map[string]validator.PropField {
	for _, iface := range widget.Contract.Props {
		if len(iface.Fields) > 0 {
			return iface.Fields
		}
	}
	return map[string]validator.PropField{"subject": {Type: "unknown", Required: true}}
}

func collectAliases(rt ResolvedTemplate) []string {
	aliases := map[string]bool{
		"PresentationRef":           true,
		"PresentationActionRequest": true,
	}
	add := func(t string) {
		for _, token := range identifiers(t) {
			if isPrimitiveType(token) || isReservedWord(token) {
				continue
			}
			aliases[token] = true
		}
	}
	for _, field := range fieldsForWidget(rt.Template) {
		add(field.Type)
	}
	for _, slot := range rt.Template.Contract.ActionSlots {
		add(slot.Accepts)
	}
	out := sortedKeys(aliases)
	return out
}

var identRe = regexp.MustCompile(`[A-Za-z_][A-Za-z0-9_]*`)

func identifiers(s string) []string { return identRe.FindAllString(s, -1) }

func isPrimitiveType(s string) bool {
	switch s {
	case "string", "number", "boolean", "unknown", "void", "integer", "true", "false":
		return true
	default:
		return false
	}
}

func isReservedWord(s string) bool {
	switch s {
	case "type", "const", "let", "var", "export", "import", "from", "null", "undefined":
		return true
	default:
		return false
	}
}

func tsType(t string) string {
	if t == "" {
		return "unknown"
	}
	if t == "integer" {
		return "number"
	}
	return t
}

func tsField(s string) string {
	if identRe.FindString(s) == s {
		return s
	}
	return fmt.Sprintf("%q", s)
}

func exportName(s string) string {
	parts := regexp.MustCompile(`[^A-Za-z0-9]+`).Split(s, -1)
	var out string
	for _, p := range parts {
		if p == "" {
			continue
		}
		out += strings.ToUpper(p[:1]) + p[1:]
	}
	if out == "" {
		return "Default"
	}
	return out
}

func hasSemanticContext(ctx validator.WidgetSemanticContext) bool {
	return len(ctx.Archetypes) > 0 || len(ctx.Capabilities) > 0 || len(ctx.Presentations) > 0 || ctx.Intent != "" || ctx.InheritedContextNote != ""
}

func hasProjectionHints(hints validator.WidgetProjectionHints) bool {
	return len(hints.Required) > 0 || len(hints.Recommended) > 0 || len(hints.Optional) > 0 || len(hints.DocumentationOnly) > 0 || len(hints.AdapterTODOs) > 0
}

func hasWidgetReflection(reflection WidgetReflection) bool {
	return len(reflection.Archetypes) > 0 || len(reflection.Capabilities) > 0 || len(reflection.Presentations) > 0
}

func semanticContextPayload(ctx validator.WidgetSemanticContext) map[string]any {
	return map[string]any{
		"archetypes":           ctx.Archetypes,
		"capabilities":         ctx.Capabilities,
		"presentations":        ctx.Presentations,
		"intent":               ctx.Intent,
		"inheritedContextNote": ctx.InheritedContextNote,
	}
}

func projectionHintsPayload(hints validator.WidgetProjectionHints) map[string]any {
	return map[string]any{
		"required":          hints.Required,
		"recommended":       hints.Recommended,
		"optional":          hints.Optional,
		"documentationOnly": hints.DocumentationOnly,
		"adapterTODOs":      hints.AdapterTODOs,
	}
}

func semanticContextSummary(ctx validator.WidgetSemanticContext) string {
	parts := []string{}
	parts = append(parts, prefixedValues("archetypes", ctx.Archetypes)...)
	parts = append(parts, prefixedValues("capabilities", ctx.Capabilities)...)
	parts = append(parts, prefixedValues("presentations", ctx.Presentations)...)
	if len(parts) == 0 && ctx.Intent != "" {
		return "intent-only"
	}
	return strings.Join(parts, ", ")
}

func projectionHintSummary(hints validator.WidgetProjectionHints) string {
	parts := []string{}
	if len(hints.Required) > 0 {
		parts = append(parts, fmt.Sprintf("%d required", len(hints.Required)))
	}
	if len(hints.Recommended) > 0 {
		parts = append(parts, fmt.Sprintf("%d recommended", len(hints.Recommended)))
	}
	if len(hints.Optional) > 0 {
		parts = append(parts, fmt.Sprintf("%d optional", len(hints.Optional)))
	}
	if len(hints.DocumentationOnly) > 0 {
		parts = append(parts, fmt.Sprintf("%d documentation-only", len(hints.DocumentationOnly)))
	}
	if len(hints.AdapterTODOs) > 0 {
		parts = append(parts, fmt.Sprintf("%d adapter TODOs", len(hints.AdapterTODOs)))
	}
	return strings.Join(parts, ", ")
}

func prefixedValues(prefix string, values []string) []string {
	out := make([]string, 0, len(values))
	for _, value := range values {
		out = append(out, prefix+":"+value)
	}
	return out
}

func writeDocList(b *strings.Builder, label string, values []string) {
	if len(values) == 0 {
		return
	}
	b.WriteString(fmt.Sprintf(" * %s:\n", label))
	for _, value := range values {
		b.WriteString(fmt.Sprintf(" * - %s\n", value))
	}
}

func writeReflectionDocLines(b *strings.Builder, reflection WidgetReflection) {
	for _, arch := range reflection.Archetypes {
		b.WriteString(fmt.Sprintf(" * - Archetype %s", arch.ID))
		if len(arch.Ancestors) > 0 {
			b.WriteString(fmt.Sprintf(" (ancestors: %s)", strings.Join(arch.Ancestors, " -> ")))
		}
		b.WriteString("\n")
		if len(arch.EffectiveDefaultCapabilities) > 0 {
			b.WriteString(fmt.Sprintf(" *   effective capabilities: %s\n", strings.Join(arch.EffectiveDefaultCapabilities, ", ")))
		}
	}
	for _, cap := range reflection.Capabilities {
		b.WriteString(fmt.Sprintf(" * - Capability %s", cap.ID))
		if len(cap.Ancestors) > 0 {
			b.WriteString(fmt.Sprintf(" (ancestors: %s)", strings.Join(cap.Ancestors, " -> ")))
		}
		b.WriteString("\n")
		if len(cap.EffectiveProjectionNames) > 0 {
			b.WriteString(fmt.Sprintf(" *   effective projections: %s\n", strings.Join(cap.EffectiveProjectionNames, ", ")))
		}
	}
	for _, pres := range reflection.Presentations {
		b.WriteString(fmt.Sprintf(" * - Presentation %s", pres.ID))
		if pres.Role != "" {
			b.WriteString(fmt.Sprintf(" (role: %s)", pres.Role))
		}
		b.WriteString("\n")
	}
}

func reflectionSummary(reflection WidgetReflection) string {
	parts := []string{}
	if len(reflection.Archetypes) > 0 {
		parts = append(parts, fmt.Sprintf("%d resolved archetypes", len(reflection.Archetypes)))
	}
	if len(reflection.Capabilities) > 0 {
		parts = append(parts, fmt.Sprintf("%d resolved capabilities", len(reflection.Capabilities)))
	}
	if len(reflection.Presentations) > 0 {
		parts = append(parts, fmt.Sprintf("%d resolved presentations", len(reflection.Presentations)))
	}
	return strings.Join(parts, ", ")
}

func writeWrappedDocLines(b *strings.Builder, text string) {
	for _, line := range strings.Split(text, "\n") {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		b.WriteString(fmt.Sprintf(" * %s\n", line))
	}
}

func tsString(s string) string {
	b, _ := json.Marshal(s)
	return string(b)
}

func sortedKeys[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
