// Code generated by logcopter-gen; DO NOT EDIT.

package profile

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("go-go-golems.dmeta.pkg.dmeta.metadesign.pbui.profile")
