// Code generated by dmeta scaffold-pbui-react-app. DO NOT EDIT until promoted.
// Generated at: 2026-05-25T03:34:10Z
// Command: /tmp/go-build4225343180/b001/exe/dmeta scaffold-pbui-react-app --root ./examples/street-deli-ordering --interactions-root ./sources/dmeta-ir --pbui-root ./sources/dmeta-ir/meta-design-systems/pbui --profile-root ./examples/street-deli-ordering/meta-design-systems/pbui --output-dir ./examples/street-deli-ordering/www/clim-react --force --output table
// Metadata: dmetaGeneratedMetadata is parseable provenance for tooling and LLM-assisted development.

export const dmetaGeneratedMetadata = {
  "schemaVersion": 1,
  "generated": {
    "at": "2026-05-25T03:34:10Z",
    "by": "dmeta scaffold-pbui-react-app",
    "command": "/tmp/go-build4225343180/b001/exe/dmeta scaffold-pbui-react-app --root ./examples/street-deli-ordering --interactions-root ./sources/dmeta-ir --pbui-root ./sources/dmeta-ir/meta-design-systems/pbui --profile-root ./examples/street-deli-ordering/meta-design-systems/pbui --output-dir ./examples/street-deli-ordering/www/clim-react --force --output table",
    "workingDirectory": "/home/manuel/code/wesen/go-go-golems/dmeta",
    "gitCommit": "450d078d3d8c4f6f01825d62d896af7ff94d2c22"
  },
  "artifact": {
    "path": "examples/street-deli-ordering/www/clim-react/src/views/HelpView.stories.tsx",
    "kind": "view_story",
    "language": "tsx",
    "symbol": "HelpViewStories",
    "promotable": true
  },
  "pipeline": {
    "semanticRoot": "./examples/street-deli-ordering",
    "interactionsRoot": "./sources/dmeta-ir",
    "metaDesignSystem": "pbui",
    "profileRoot": "./examples/street-deli-ordering/meta-design-systems/pbui",
    "target": "react_app",
    "passes": [
      "semantic-ir",
      "interaction-elaboration",
      "pbui-lowering",
      "pbui-presentation-profile-instantiation",
      "pbui-react-app-planning"
    ]
  },
  "sources": [
    {
      "path": "./examples/street-deli-ordering",
      "role": "semantic package",
      "why": "Provides Street Deli domain types, archetypes, capabilities, and examples."
    },
    {
      "path": "./sources/dmeta-ir",
      "role": "interaction package",
      "why": "Provides actions and representations used by PBUI lowering."
    },
    {
      "path": "./sources/dmeta-ir/meta-design-systems/pbui",
      "role": "PBUI MetaDesignSystem",
      "why": "Provides abstract PBUI presentation types and lowering rules."
    },
    {
      "path": "./examples/street-deli-ordering/meta-design-systems/pbui",
      "role": "concrete PBUI profile",
      "why": "Provides presentation-system, style, surface, view-model, and presentation-binding guidance for the CLIM React app."
    }
  ],
  "pbui": {
    "viewId": "help",
    "surfaceId": "view",
    "bindingComponent": "HelpView",
    "styleClasses": [
      "street_deli_clim_mono"
    ]
  },
  "react": {
    "packageName": "street-deli-clim-react"
  },
  "guidance": {
    "summary": "Generated concrete PBUI/CLIM React app artifact. This file is part of the promotable Street Deli CLIM app scaffold and should retain profile metadata when edited.",
    "implementationNotes": [
      "Use dmetaGeneratedMetadata to trace this app code back to Semantic IR, Interaction IR, PBUI MetaDesignSystem, and the concrete presentation profile.",
      "Presentation bindings, surfaces, view models, and style-profile choices live under the concrete profile root.",
      "When promoting this file, append behavioral and visual edits to the promotion changelog before changing runtime behavior."
    ]
  },
  "promotion": {
    "promotable": true,
    "status": "scaffold",
    "instructions": [
      "Keep dmetaGeneratedMetadata unless this file is deliberately detached from DMETA.",
      "Record semantic, behavioral, prop, or visual changes in the promotion changelog.",
      "Update Storybook coverage when visual states or interaction behavior change."
    ],
    "changelog": [
      "2026-05-25T03:34:10Z: Generated by dmeta scaffold-pbui-react-app. Initial scaffold."
    ]
  }
} as const;

/**
 * DMETA promotion status: scaffold
 *
 * Promotion instructions:
 * - Keep dmetaGeneratedMetadata unless this file is deliberately detached from DMETA.
 * - Record semantic, behavioral, prop, or visual changes in the promotion changelog.
 * - Update Storybook coverage when visual states or interaction behavior change.
 *
 * Promotion changelog:
 * - 2026-05-25T03:34:10Z: Generated by dmeta scaffold-pbui-react-app. Initial scaffold.
 */

import type { Meta, StoryObj } from '@storybook/react-vite';
import { ClimStoryShell } from '../components/storybook/ClimStoryShell';
import { HelpView } from './HelpView';

const meta = {
  title: 'CLIM/Views/HelpView',
  component: HelpView,
  decorators: [(Story) => <ClimStoryShell modeLabel="MENU"><Story /></ClimStoryShell>],
} satisfies Meta<typeof HelpView>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {};
