package core

import (
	"context"
	"path/filepath"
	"runtime"
	"strings"
	"testing"

	"github.com/go-go-golems/dmeta/pkg/dmeta/validator"
)

func TestGenerateCurrentCoreSmoke(t *testing.T) {
	root := repoRoot(t)
	pkg, err := validator.LoadPackage(context.Background(), filepath.Join(root, "sources", "dmeta-ir"))
	if err != nil {
		t.Fatalf("load package: %v", err)
	}

	files, err := Generate(pkg, "generated/dmeta-core")
	if err != nil {
		t.Fatalf("generate: %v", err)
	}
	if got, want := len(files), 3; got != want {
		t.Fatalf("expected %d files, got %d", want, got)
	}

	byPath := map[string]string{}
	for _, file := range files {
		byPath[file.Path] = string(file.Content)
		if !strings.Contains(string(file.Content), "Code generated by dmeta generate-core") {
			t.Fatalf("%s missing generated header", file.Path)
		}
	}

	assertContains(t, byPath["generated/dmeta-core/archetypes.ts"], "export type ArchetypeId")
	assertContains(t, byPath["generated/dmeta-core/archetypes.ts"], "longDescription")
	assertContains(t, byPath["generated/dmeta-core/archetypes.ts"], "ancestors")
	assertContains(t, byPath["generated/dmeta-core/archetypes.ts"], "effectiveDefaultCapabilities")
	assertContains(t, byPath["generated/dmeta-core/archetypes.ts"], "isArchetypeA")
	assertContains(t, byPath["generated/dmeta-core/capabilities.ts"], "export type CapabilityId")
	assertContains(t, byPath["generated/dmeta-core/capabilities.ts"], "effectiveProjections")
	assertContains(t, byPath["generated/dmeta-core/capabilities.ts"], "isCapabilityA")
	assertContains(t, byPath["generated/dmeta-core/index.ts"], "./archetypes")
	assertContains(t, byPath["generated/dmeta-core/index.ts"], "./capabilities")
}

func TestGenerateCurrentCoreDeterministic(t *testing.T) {
	root := repoRoot(t)
	pkg, err := validator.LoadPackage(context.Background(), filepath.Join(root, "sources", "dmeta-ir"))
	if err != nil {
		t.Fatalf("load package: %v", err)
	}

	first, err := Generate(pkg, "generated/dmeta-core")
	if err != nil {
		t.Fatalf("first generate: %v", err)
	}
	second, err := Generate(pkg, "generated/dmeta-core")
	if err != nil {
		t.Fatalf("second generate: %v", err)
	}
	if len(first) != len(second) {
		t.Fatalf("file count mismatch: %d != %d", len(first), len(second))
	}
	for i := range first {
		if first[i].Path != second[i].Path {
			t.Fatalf("path mismatch at %d: %s != %s", i, first[i].Path, second[i].Path)
		}
		if string(first[i].Content) != string(second[i].Content) {
			t.Fatalf("content mismatch for %s", first[i].Path)
		}
	}
}

func repoRoot(t *testing.T) string {
	t.Helper()
	_, file, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("runtime.Caller failed")
	}
	return filepath.Clean(filepath.Join(filepath.Dir(file), "..", "..", "..", ".."))
}

func assertContains(t *testing.T, s string, want string) {
	t.Helper()
	if !strings.Contains(s, want) {
		t.Fatalf("expected generated content to contain %q", want)
	}
}
