package core

import (
	"bytes"
	"encoding/json"
	"fmt"
	"sort"
	"strings"

	"github.com/go-go-golems/dmeta/pkg/dmeta/validator"
)

const generatedHeader = "// Code generated by dmeta generate-core from sources/dmeta-ir/01-core-model.yaml and core-model/*.yaml. DO NOT EDIT.\n\n"

func Generate(pkg *validator.Package, outDir string) ([]GeneratedFile, error) {
	if pkg == nil {
		return nil, fmt.Errorf("nil validator package")
	}
	resolved, findings := validator.ResolveCoreInheritance(pkg.CoreModel)
	if validator.HasErrors(findings) {
		for _, finding := range findings {
			if finding.Severity == validator.SeverityError {
				return nil, fmt.Errorf("resolve core inheritance: %s: %s", finding.Code, finding.Message)
			}
		}
	}
	if outDir == "" {
		outDir = "generated/dmeta-core"
	}
	files := []GeneratedFile{
		{Path: joinOut(outDir, "archetypes.ts"), Content: []byte(renderArchetypes(pkg.CoreModel, resolved))},
		{Path: joinOut(outDir, "capabilities.ts"), Content: []byte(renderCapabilities(pkg.CoreModel, resolved))},
		{Path: joinOut(outDir, "index.ts"), Content: []byte(RenderIndex())},
	}
	return files, nil
}

func RenderArchetypes(core validator.CoreModelFile) string {
	resolved, _ := validator.ResolveCoreInheritance(core)
	return renderArchetypes(core, resolved)
}

func renderArchetypes(core validator.CoreModelFile, resolved *validator.ResolvedCoreModel) string {
	var b bytes.Buffer
	b.WriteString(generatedHeader)
	b.WriteString("import type { CapabilityId } from \"./capabilities\";\n\n")
	ids := sortedKeys(core.Archetypes)
	renderConstStringArray(&b, "archetypeIds", ids)
	b.WriteString("export type ArchetypeId = typeof archetypeIds[number];\n\n")
	b.WriteString(`export type ArchetypeDefinition = {
  id: ArchetypeId;
  description: string;
  longDescription: string;
  extends: ArchetypeId[];
  abstract: boolean;
  ancestors: ArchetypeId[];
  defaultCapabilities: CapabilityId[];
  effectiveDefaultCapabilities: CapabilityId[];
  examples: string[];
  effectiveExamples: string[];
};

`)
	b.WriteString("export const archetypes: Record<ArchetypeId, ArchetypeDefinition> = {\n")
	for _, id := range ids {
		a := core.Archetypes[id]
		ra := resolved.Archetypes[id]
		b.WriteString(fmt.Sprintf("  %s: {\n", tsProperty(id)))
		b.WriteString(fmt.Sprintf("    id: %s,\n", tsString(id)))
		b.WriteString(fmt.Sprintf("    description: %s,\n", tsString(a.Description)))
		b.WriteString(fmt.Sprintf("    longDescription: %s,\n", tsString(a.LongDescription)))
		b.WriteString(fmt.Sprintf("    extends: %s as ArchetypeId[],\n", tsArray(a.Extends)))
		b.WriteString(fmt.Sprintf("    abstract: %t,\n", a.Abstract))
		b.WriteString(fmt.Sprintf("    ancestors: %s as ArchetypeId[],\n", tsArray(ra.Ancestors)))
		b.WriteString(fmt.Sprintf("    defaultCapabilities: %s as CapabilityId[],\n", tsArray(a.DefaultCapabilities)))
		b.WriteString(fmt.Sprintf("    effectiveDefaultCapabilities: %s as CapabilityId[],\n", tsArray(ra.EffectiveDefaultCapabilities)))
		b.WriteString(fmt.Sprintf("    examples: %s,\n", tsArray(a.Examples)))
		b.WriteString(fmt.Sprintf("    effectiveExamples: %s,\n", tsArray(ra.EffectiveExamples)))
		b.WriteString("  },\n")
	}
	b.WriteString("};\n\n")
	b.WriteString(`export function isArchetypeId(value: string): value is ArchetypeId {
  return (archetypeIds as readonly string[]).includes(value);
}

export function isArchetypeA(child: ArchetypeId, ancestor: ArchetypeId): boolean {
  return child === ancestor || archetypes[child].ancestors.includes(ancestor);
}

export function archetypeHasCapability(archetype: ArchetypeId, capability: CapabilityId): boolean {
  return archetypes[archetype].effectiveDefaultCapabilities.includes(capability);
}
`)
	return b.String()
}

func RenderCapabilities(core validator.CoreModelFile) string {
	resolved, _ := validator.ResolveCoreInheritance(core)
	return renderCapabilities(core, resolved)
}

func renderCapabilities(core validator.CoreModelFile, resolved *validator.ResolvedCoreModel) string {
	var b bytes.Buffer
	b.WriteString(generatedHeader)
	ids := sortedKeys(core.Capabilities)
	renderConstStringArray(&b, "capabilityIds", ids)
	b.WriteString("export type CapabilityId = typeof capabilityIds[number];\n\n")
	b.WriteString(`export type ProjectionDefinition = {
  name: string;
  type: string;
  required: boolean;
  description: string;
};

export type CapabilityDefinition = {
  id: CapabilityId;
  description: string;
  longDescription: string;
  extends: CapabilityId[];
  abstract: boolean;
  ancestors: CapabilityId[];
  projections: Record<string, ProjectionDefinition>;
  effectiveProjections: Record<string, ProjectionDefinition>;
};

`)
	b.WriteString("export const capabilities: Record<CapabilityId, CapabilityDefinition> = {\n")
	for _, id := range ids {
		c := core.Capabilities[id]
		rc := resolved.Capabilities[id]
		b.WriteString(fmt.Sprintf("  %s: {\n", tsProperty(id)))
		b.WriteString(fmt.Sprintf("    id: %s,\n", tsString(id)))
		b.WriteString(fmt.Sprintf("    description: %s,\n", tsString(c.Description)))
		b.WriteString(fmt.Sprintf("    longDescription: %s,\n", tsString(c.LongDescription)))
		b.WriteString(fmt.Sprintf("    extends: %s as CapabilityId[],\n", tsArray(c.Extends)))
		b.WriteString(fmt.Sprintf("    abstract: %t,\n", c.Abstract))
		b.WriteString(fmt.Sprintf("    ancestors: %s as CapabilityId[],\n", tsArray(rc.Ancestors)))
		b.WriteString("    projections: ")
		renderProjectionMap(&b, c.Projections)
		b.WriteString(",\n")
		b.WriteString("    effectiveProjections: ")
		renderProjectionMap(&b, rc.EffectiveProjections)
		b.WriteString(",\n")
		b.WriteString("  },\n")
	}
	b.WriteString("};\n\n")
	b.WriteString(`export function isCapabilityId(value: string): value is CapabilityId {
  return (capabilityIds as readonly string[]).includes(value);
}

export function isCapabilityA(child: CapabilityId, ancestor: CapabilityId): boolean {
  return child === ancestor || capabilities[child].ancestors.includes(ancestor);
}
`)
	return b.String()
}

func RenderIndex() string {
	return generatedHeader + `export * from "./archetypes";
export * from "./capabilities";
`
}

func renderProjectionMap(b *bytes.Buffer, projections map[string]validator.Projection) {
	if len(projections) == 0 {
		b.WriteString("{}")
		return
	}
	b.WriteString("{\n")
	for _, projID := range sortedKeys(projections) {
		p := projections[projID]
		b.WriteString(fmt.Sprintf("      %s: { name: %s, type: %s, required: %t, description: %s },\n", tsProperty(projID), tsString(projID), tsString(p.Type), p.Required, tsString(p.Description)))
	}
	b.WriteString("    }")
}

func renderConstStringArray(b *bytes.Buffer, name string, values []string) {
	b.WriteString(fmt.Sprintf("export const %s = [\n", name))
	for _, value := range values {
		b.WriteString(fmt.Sprintf("  %s,\n", tsString(value)))
	}
	b.WriteString("] as const;\n\n")
}

func sortedKeys[T any](m map[string]T) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func tsString(s string) string {
	b, _ := json.Marshal(s)
	return string(b)
}

func tsArray(values []string) string {
	if len(values) == 0 {
		return "[]"
	}
	parts := make([]string, len(values))
	for i, value := range values {
		parts[i] = tsString(value)
	}
	return "[" + strings.Join(parts, ", ") + "]"
}

func tsBoolMap(values map[string]bool) string {
	if len(values) == 0 {
		return "{}"
	}
	keys := sortedKeys(values)
	parts := make([]string, 0, len(keys))
	for _, key := range keys {
		parts = append(parts, fmt.Sprintf("%s: %t", tsProperty(key), values[key]))
	}
	return "{ " + strings.Join(parts, ", ") + " }"
}

func tsProperty(s string) string {
	if isTSIdentifier(s) {
		return s
	}
	return tsString(s)
}

func isTSIdentifier(s string) bool {
	if s == "" {
		return false
	}
	for i, r := range s {
		if i == 0 {
			if !(r == '_' || r == '$' || (r >= 'A' && r <= 'Z') || (r >= 'a' && r <= 'z')) {
				return false
			}
			continue
		}
		if !(r == '_' || r == '$' || (r >= 'A' && r <= 'Z') || (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9')) {
			return false
		}
	}
	return true
}

func joinOut(outDir, file string) string {
	return strings.TrimRight(outDir, "/") + "/" + file
}
